- .github/workflows/release.yml
- scripts/build-images.sh
- scripts/packager-repo.sh
- src/frontend/.eslintrc.js
- src/frontend/devops-op/src/router/index.js
- src/frontend/devops-op/src/views/job/index.vue
- src/frontend/devops-repository/src/components/PackageCard/index.vue
- src/frontend/devops-repository/src/store/publicEnum.js
- src/frontend/devops-repository/src/views/index.vue
- src/frontend/devops-repository/src/views/repoCommon/commonPackageDetail.vue
- src/frontend/devops-repository/src/views/repoCommon/commonVersionDetail.vue
- src/frontend/devops-repository/src/views/repoConfig/index.vue
- src/frontend/devops-repository/src/views/repoGeneric/index.vue
- src/frontend/devops-repository/src/views/repoList/createRepoDialog.vue
- src/frontend/devops-repository/webpack.config.js
- support-files/kubernetes/images/build.sh
1. 根据RELEASE_MODE设置是否展示菜单项
2. 移除发布的制品版本v前缀
close #22
> feat: 根据RELEASE_MODE设置是否展示菜单项，移除发布的制品版本v前缀

- src/frontend/devops-op/src/store/modules/user.js
- src/frontend/devops-op/src/views/login/index.vue
> fix: 增加登入失败时的提示信息 #31

- src/backend/buildSrc/src/main/kotlin/Versions.kt
- src/backend/common/common-api/src/main/kotlin/com/tencent/bkrepo/common/api/thread/TransmittableInheritableThreadLocal.kt
- src/backend/common/common-api/src/main/kotlin/com/tencent/bkrepo/common/api/thread/TransmittableThreadLocal.kt
- src/backend/settings.gradle.kts
> feat: 升级devops-framework版本 #73

- src/backend/buildSrc/src/main/kotlin/Versions.kt
> feat: 回滚devops-framework到0.0.6 #73

- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/controller/user/UserNodeController.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/node/NodeDeleteOperation.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/node/impl/NodeDeleteSupport.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/node/impl/NodeServiceImpl.kt
> feat：制品库批量删除文件或目录 #58

- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/node/impl/NodeDeleteSupport.kt
> feat：制品库批量删除文件或目录问题修复 #58

- src/frontend/devops-op/src/views/node/index.vue
> bug: 修复制品库Admin下载文件包含中文时出错 #123

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/TemporaryScanTokenServiceImpl.kt
> bug: 修复扫描器拉取到的任务超时时间计算错误 #172

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/ScanPlanServiceImpl.kt
> bug: 修复扫描器被删除后列出制品可用扫描方案失败 #170

- src/backend/analysis-executor/biz-analysis-executor/src/main/kotlin/com/tencent/bkrepo/analysis/executor/ExecutorScheduler.kt
- src/backend/analysis-executor/biz-analysis-executor/src/main/kotlin/com/tencent/bkrepo/analysis/executor/controller/ExecutorController.kt
- src/backend/analyst/biz-analyst/build.gradle.kts
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/component/AnalystLoadBalancer.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/configuration/AnalysisLoadBalancerConfiguration.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/configuration/ScannerConfiguration.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dispatcher/SubtaskPoller.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/ScanServiceImpl.kt
> feat: 支持停止扫描任务后中止扫描容器 #161

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/statemachine/iterator/IteratorManager.kt
- src/frontend/devops-op/src/views/scan/components/CreateOrUpdateScannerDialog.vue
- src/frontend/devops-repository/src/store/actions/scan.js
- src/frontend/devops-repository/src/views/repoGeneric/genericFormDialog.vue
- src/frontend/devops-repository/src/views/repoGeneric/index.vue
> feat: 支持扫描无后缀文件 #219

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/ProjectScanConfigurationServiceImpl.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/statemachine/task/action/PendingAction.kt
- src/backend/common/common-analysis/src/main/kotlin/com/tencent/bkrepo/common/analysis/pojo/scanner/Scanner.kt
- src/frontend/devops-op/src/api/scan.js
- src/frontend/devops-op/src/views/scan/components/CreateOrUpdateProjectScanConfigurationDialog.vue
- src/frontend/devops-op/src/views/scan/components/CreateOrUpdateScannerDialog.vue
CLOSE #217
目前支持将制品分析任务分发到多个不同的执行集群，但是不同分析工具支持的执行环境不一样，需要为分析工具设置支持的执行环境
> feat: 支持设置分析工具支持的分发器 #217

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/configuration/KubernetesDispatcherProperties.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dispatcher/KubernetesDispatcher.kt
> 修复小文件由于文件大小限制导致扫描失败

- src/backend/analysis-executor/biz-analysis-executor/src/main/kotlin/com/tencent/bkrepo/analysis/executor/configuration/ScannerExecutorProperties.kt
- src/backend/analysis-executor/biz-analysis-executor/src/main/kotlin/com/tencent/bkrepo/analysis/executor/util/DockerScanHelper.kt
- src/backend/common/common-analysis/src/main/kotlin/com/tencent/bkrepo/common/analysis/pojo/scanner/arrowhead/ArrowheadScanner.kt
- src/backend/common/common-analysis/src/main/kotlin/com/tencent/bkrepo/common/analysis/pojo/scanner/utils/DockerUtils.kt
> feat: 输出制品分析容器执行日志 #205

- src/backend/common/common-api/src/main/kotlin/com/tencent/bkrepo/common/api/constant/Constants.kt
- src/backend/maven/api-maven/src/main/kotlin/com/tencent/bkrepo/maven/api/MavenMetadataClient.kt
- src/backend/maven/api-maven/src/main/kotlin/com/tencent/bkrepo/maven/pojo/metadata/MavenMetadataRequest.kt
- src/backend/maven/biz-maven/src/main/kotlin/com/tencent/bkrepo/maven/controller/service/MavenMetadataController.kt
- src/backend/maven/biz-maven/src/main/kotlin/com/tencent/bkrepo/maven/dao/MavenMetadataDao.kt
- src/backend/maven/biz-maven/src/main/kotlin/com/tencent/bkrepo/maven/service/MavenMetadataService.kt
- src/backend/maven/biz-maven/src/main/kotlin/com/tencent/bkrepo/maven/service/impl/edge/EdgeMavenMetadataService.kt
- src/backend/repository/api-repository/src/main/kotlin/com/tencent/bkrepo/repository/api/StageClient.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/controller/service/StageController.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/dao/PackageDao.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/dao/PackageVersionDao.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/model/ClusterResource.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/model/TPackage.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/model/TPackageVersion.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/packages/impl/PackageBaseService.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/packages/impl/PackageDependentsServiceImpl.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/packages/impl/PackageServiceImpl.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/packages/impl/StageServiceImpl.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/packages/impl/center/CommitEdgeCenterPackageDependentsServiceImpl.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/packages/impl/center/CommitEdgeCenterPackageServiceImpl.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/packages/impl/center/CommitEdgeCenterStageServiceImpl.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/packages/impl/edge/EdgePackageDependentsServiceImpl.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/packages/impl/edge/EdgeStageServiceImpl.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/util/ClusterUtils.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/util/PackageQueryHelper.kt
> feat: 支持Package通过CommitEdge同步 #224

- src/backend/common/common-notify/notify-service/src/main/kotlin/com/tencent/bkrepo/common/notify/client/weworkbot/WeworkBotClient.kt
> feat: 调整分析结果通知错误日志级别 #365

- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/Constants.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/DeletedNodeCleanupJob.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/context/DeletedNodeCleanupJobContext.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/utils/MongoShardingUtils.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/dao/RepositoryDao.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/job/DeletedNodeCleanupJob.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/model/TRepository.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/repo/impl/QuotaServiceImpl.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/repo/impl/RepositoryServiceImpl.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/repo/impl/SoftwareRepositoryServiceImpl.kt
- src/backend/repository/biz-repository/src/test/kotlin/com/tencent/bkrepo/repository/service/RepositoryServiceTest.kt
删除仓库时标记deleted字段，节点清理任务判断已删除仓库内没有节点时才把仓库数据删除(issue #30)
> fix: 删除仓库后已标记删除但未清理的节点无法被清理 #30

- src/frontend/devops-repository/src/views/index.vue
feat: p1_26547 【CPack】制品分发菜单修改为系统管理员权限可见且是系统级显示
> feat: p1_26547 【CPack】制品分发菜单修改为系统管理员权限可见且是系统级显示 #396

- src/frontend/devops-repository/src/views/repoScan/scanConfig/scanQualityRule.vue
fix: 制品分析 > 方案设置页面代码不满足eslint规范 #422
> fix: 制品分析 > 方案设置页面代码不满足eslint规范 #422

- src/frontend/devops-repository/src/components/CardRadioGroup/index.vue
- src/frontend/devops-repository/src/views/repoConfig/index.vue
- src/frontend/devops-repository/src/views/repoList/createRepoDialog.vue
fix: 创建仓库弹窗中英文状态下访问权限的卡片宽度过大，导致描述超出卡片限制区域
> fix: 创建仓库弹窗中英文状态下访问权限的卡片宽度过大，导致描述超出卡片限制区域 #413

- src/frontend/devops-repository/src/scss/reset.scss
> style: 分页器显示效果修改 #414

- src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/manager/PermissionManager.kt
> bug: 修复判断是否允许读取系统公开仓库时未使用传入的用户 #418

- src/backend/common/common-operate/operate-service/src/main/kotlin/com/tencent/bkrepo/common/operate/service/OperateAutoConfiguration.kt
> bug: 修复存在多个operateLogService导致的分析服务启动失败 #497

- src/frontend/devops-repository/src/store/publicEnum.js
- src/frontend/locale/repository/en-US.json
- src/frontend/locale/repository/zh-CN.json
> feat: 支持NPM制品分析 #495

- src/backend/analysis-executor/biz-analysis-executor/src/main/kotlin/com/tencent/bkrepo/analysis/executor/pojo/ScanExecutorTask.kt
- src/backend/analysis-executor/biz-analysis-executor/src/main/kotlin/com/tencent/bkrepo/analysis/executor/standard/StandardScanExecutor.kt
- src/backend/analysis-executor/biz-analysis-executor/src/main/kotlin/com/tencent/bkrepo/analysis/executor/util/Converter.kt
- src/backend/analyst/api-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/pojo/SubScanTask.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/TemporaryScanTokenServiceImpl.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/utils/SubtaskConverter.kt
- src/backend/common/common-analysis/src/main/kotlin/com/tencent/bkrepo/common/analysis/pojo/scanner/standard/StandardScanner.kt
- src/backend/common/common-analysis/src/main/kotlin/com/tencent/bkrepo/common/analysis/pojo/scanner/standard/ToolInput.kt
> feat: 添加包类型与版本到标准扫描器参数 #499

- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/controller/user/UserPackageRepairController.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/dao/PackageVersionDao.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/packages/PackageRepairService.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/packages/impl/PackageRepairServiceImpl.kt
> feature: 提供接口重新计算并修正所有制品包的版本数量 #459

- src/backend/analyst/api-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/pojo/SubScanTask.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/controller/ScanController.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/event/ScanEventConsumer.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/ScanService.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/ScanServiceImpl.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/TemporaryScanTokenServiceImpl.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/statemachine/task/action/PendingAction.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/statemachine/task/context/CreateTaskContext.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/utils/SubtaskConverter.kt
> bug: 修复制品分析拉取制品时401错误 #550

- src/backend/analyst/api-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/pojo/SubScanTask.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/controller/ScanController.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/event/ScanEventConsumer.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/ScanService.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/ScanServiceImpl.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/TemporaryScanTokenServiceImpl.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/statemachine/task/action/PendingAction.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/statemachine/task/context/CreateTaskContext.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/utils/SubtaskConverter.kt
- src/backend/auth/biz-auth/src/main/kotlin/com/tencent/bkrepo/auth/condition/BkDevopsAuthCondition.kt
- src/backend/auth/biz-auth/src/main/kotlin/com/tencent/bkrepo/auth/config/AuthServiceConfig.kt
- src/backend/auth/biz-auth/src/main/kotlin/com/tencent/bkrepo/auth/config/BkAuthConfig.kt
- src/backend/auth/biz-auth/src/main/kotlin/com/tencent/bkrepo/auth/controller/service/ServicePipelineController.kt
- src/backend/auth/biz-auth/src/main/kotlin/com/tencent/bkrepo/auth/repository/UserRepository.kt
- src/backend/auth/biz-auth/src/main/kotlin/com/tencent/bkrepo/auth/service/PermissionService.kt
- src/backend/auth/biz-auth/src/main/kotlin/com/tencent/bkrepo/auth/service/bkauth/BkAuthPermissionServiceImpl.kt
- src/backend/auth/biz-auth/src/main/kotlin/com/tencent/bkrepo/auth/service/bkauth/BkAuthPipelineService.kt
- src/backend/auth/biz-auth/src/main/kotlin/com/tencent/bkrepo/auth/service/bkauth/BkAuthProjectService.kt
- src/backend/auth/biz-auth/src/main/kotlin/com/tencent/bkrepo/auth/service/bkauth/BkciAuthService.kt
- src/backend/auth/biz-auth/src/main/kotlin/com/tencent/bkrepo/auth/service/local/AbstractServiceImpl.kt
- src/backend/auth/biz-auth/src/main/kotlin/com/tencent/bkrepo/auth/service/local/PermissionServiceImpl.kt
- src/backend/auth/biz-auth/src/main/kotlin/com/tencent/bkrepo/auth/service/local/UserServiceImpl.kt
- src/backend/auth/boot-auth/src/test/kotlin/com/tencent/bkrepo/auth/bkiam/BkciAuthServiceTest.kt
- src/backend/replication/biz-replication/src/main/kotlin/com/tencent/bkrepo/replication/controller/service/ArtifactReplicaController.kt
- src/backend/replication/biz-replication/src/main/kotlin/com/tencent/bkrepo/replication/service/impl/ClusterNodeServiceImpl.kt
- src/frontend/devops-repository/src/store/actions/project.js
- src/frontend/devops-repository/src/views/projectManage/index.vue
- src/frontend/locale/repository/en-US.json
- src/frontend/locale/repository/zh-CN.json
Reverts TencentBlueKing/bk-repo#568
> Revert "合并master分支代码"

- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/base/MongoDbBatchJob.kt
> bug: 设置按ID范围查询数据执行定时任务时按ID排序 #566

- src/backend/analyst/api-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/pojo/report/Component.kt
- src/backend/analyst/api-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/pojo/report/Report.kt
- src/backend/analyst/api-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/pojo/report/Vulnerability.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/component/ReportExporter.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/configuration/ReportExportProperties.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/configuration/ScannerConfiguration.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/configuration/ScannerProperties.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/ScanServiceImpl.kt
> feat: 导出扫描结果报告到消息队列 #450

- src/frontend/devops-repository/src/views/repoSearch/index.vue
fix: 优化制品搜索逻辑，支持直接复制url后打开当前搜索的制品列表页 #563
> fix: 优化制品搜索逻辑，支持直接复制url后打开当前搜索的制品列表页 #563

- src/backend/opdata/biz-opdata/src/main/kotlin/com/tencent/bkrepo/opdata/controller/GrafanaController.kt
> feat: 限制匿名用户访问grafana接口 #603

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/component/ReportExporter.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/configuration/ReportExportProperties.kt
> feat: 支持通过扫描器名过滤要导出报告到计算平台的任务 #623

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/utils/Request.kt
> bug: 优化制品分析遍历制品效率 #635

- .github/workflows/label.yml
> feat: 设置提PR时检查关联的issue是否有tested标签 #613

- src/backend/analyst/api-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/pojo/AutoScanConfiguration.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/event/ScanEventConsumer.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/model/TProjectScanConfiguration.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/ProjectScanConfigurationService.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/ProjectScanConfigurationServiceImpl.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/statemachine/subtask/action/NotifySubtaskAction.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/statemachine/task/action/PendingAction.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/statemachine/task/action/SubmittingAction.kt
> feat: 支持配置全局自动扫描规则，过滤扫描器不支持的事件 #644

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dispatcher/SubtaskPoller.kt
> bug: 修复复用扫描结果时调用executor清理接口报错 #666

- src/frontend/devops-repository/src/store/actions/repoGeneric.js
> bug: 修改Generic类型仓库前端目录树排序为按修改时间倒序排 #690

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dispatcher/KubernetesDispatcher.kt
> bug: 修复在K8S创建分析任务Job时报409错误 #574

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/configuration/ScannerProperties.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/ScanServiceImpl.kt
> feat: 支持设置分析任务最大阻塞时长 #662

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/configuration/ScannerProperties.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/ScanServiceImpl.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/TemporaryScanTokenServiceImpl.kt
> bug: 修复分析任务上报状态401错误 #537

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/statemachine/iterator/PackageIterator.kt
- src/frontend/devops-repository/src/views/repoScan/scanConfig/artiTable/index.vue
> bug: 修复扫描所有制品的最新版本选项不生效 #633

- src/backend/analyst/api-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/pojo/rule/RuleArtifact.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/event/ScanEventConsumer.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/statemachine/iterator/PackageIterator.kt
> bug: 修复设置自动扫描最新版本Package类型制品不生效 #746

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/statemachine/TaskStateMachineConfiguration.kt
> bug: 修复PULLED状态转移到FAILED状态无限循环 #757

- src/frontend/devops-repository/src/views/repoScan/artiReport/license.vue
> feat: 隐藏License扫描结果OSI、FSF、推荐、合规列 #775

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/statemachine/subtask/action/FinishSubtaskAction.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/statemachine/subtask/action/ReuseResultAction.kt
> bug: 修复报告详情页质量规则未展示 #806

- src/backend/analyst/api-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/pojo/request/ScanQualityUpdateRequest.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dao/ScanPlanDao.kt
> bug: 修复更新质量规则失败 #794

- src/backend/router-controller/api-router-controller/src/main/kotlin/com/tencent/bkrepo/router/api/RouterControllerClient.kt
- src/backend/router-controller/boot-router-controller/src/main/kotlin/com/tencent/bkrepo/router/contoller/service/RouterController.kt
> feat: 支持微服务请求增加路由节点 #851

- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/node/NodeStatCompositeMongoDbBatchJob.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/utils/RepositoryCommonUtils.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/config/properties/NodeStatCompositeMongoDbBatchJobProperties.kt
> feat: 修复Job服务查询Repository缓存不生效 #843

- src/backend/common/common-artifact/artifact-api/src/main/kotlin/com/tencent/bkrepo/common/artifact/pojo/RepositoryType.kt
- src/backend/repository/api-repository/src/main/kotlin/com/tencent/bkrepo/repository/pojo/packages/PackageType.kt
> bug: 查询RDS相关数据时Json反序列化错误 #859

- src/frontend/devops-repository/src/views/repoCommon/commonPackageList.vue
- src/frontend/devops-repository/src/views/repoList/index.vue
- src/frontend/devops-repository/src/views/repoScan/artiReport/index.vue
- src/frontend/devops-repository/src/views/repoScan/index.vue
- src/frontend/devops-repository/src/views/repoScan/scanReport/filterSideslider.vue
- src/frontend/devops-repository/src/views/repoScan/scanReport/index.vue
- src/frontend/devops-repository/src/views/repoScan/scanReport/overview.vue
- src/frontend/devops-software/src/views/repoList/index.vue
feat: 制品仓库及制品分析的详情页中点击面包屑返回上层保留筛选项和页码等参数 #842
> feat: 制品仓库及制品分析的详情页中点击面包屑返回上层保留筛选项和页码等参数 #842

- src/backend/replication/biz-replication/src/main/kotlin/com/tencent/bkrepo/replication/fdtp/FdtpAFTClient.kt
- src/backend/replication/biz-replication/src/main/kotlin/com/tencent/bkrepo/replication/fdtp/FdtpAFTHelper.kt
- src/backend/replication/biz-replication/src/main/kotlin/com/tencent/bkrepo/replication/fdtp/FdtpConstants.kt
- src/backend/replication/biz-replication/src/main/kotlin/com/tencent/bkrepo/replication/fdtp/FdtpTracingHandler.kt
- src/backend/replication/biz-replication/src/main/kotlin/com/tencent/bkrepo/replication/replica/base/handler/ClusterArtifactReplicationHandler.kt
- src/backend/replication/biz-replication/src/test/kotlin/com/tencent/bkrepo/replication/fdtp/FdtpAFTTest.kt
> feat: fdtp支持traceid #726

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dao/ScanPlanDao.kt
> bug: 修复分页获取扫描方案总数量字段错误 #861

- src/backend/opdata/biz-opdata/src/main/kotlin/com/tencent/bkrepo/opdata/handler/impl/FileExtensionHandler.kt
- src/backend/opdata/biz-opdata/src/main/kotlin/com/tencent/bkrepo/opdata/handler/impl/NodeSizeDistributionHandler.kt
- src/backend/opdata/biz-opdata/src/main/kotlin/com/tencent/bkrepo/opdata/handler/impl/ProjectNumHandler.kt
- src/backend/opdata/biz-opdata/src/main/kotlin/com/tencent/bkrepo/opdata/handler/impl/StorageCredentialHandler.kt
> bug: 修复Grafana接口查询报错 #875

- src/frontend/devops-repository/src/views/planManage/planLog.vue
- src/frontend/locale/repository/en-US.json
- src/frontend/locale/repository/zh-CN.json
fix: 制品分发的日志侧弹窗中标题显示有误；#901
fix: 制品分发的日志侧弹窗中表格的表头中编号字段不能完整显示；#901
> fix: 制品分发的日志侧弹窗中标题显示有误 #901

- src/backend/npm/biz-npm/src/main/kotlin/com/tencent/bkrepo/npm/handler/NpmPackageHandler.kt
- src/backend/npm/biz-npm/src/main/kotlin/com/tencent/bkrepo/npm/service/impl/NpmClientServiceImpl.kt
- src/backend/npm/biz-npm/src/main/kotlin/com/tencent/bkrepo/npm/utils/BeanUtils.kt
> bug: 创建npm包时元数据文件的数组属性转换失败 #897

- src/frontend/devops-repository/src/views/preview/scanTask.vue
> bug: 修复扫描报告详情页无法进入 #914

- src/backend/maven/biz-maven/src/main/kotlin/com/tencent/bkrepo/maven/artifact/repository/MavenLocalRepository.kt
- src/backend/maven/biz-maven/src/main/kotlin/com/tencent/bkrepo/maven/pojo/Basic.kt
- src/frontend/devops-repository/src/views/repoCommon/repoGuideMixin.js
> feat: 非jar类型的maven制品使用指引添加type标签 #932

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/configuration/ScannerProperties.kt
> bug: 修复制品分析任务默认阻塞超时时间错误 #938

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dispatcher/KubernetesDeploymentDispatcher.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dispatcher/KubernetesDispatcher.kt
> fix: 修复调用K8S API未认证错误 #955

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/statemachine/iterator/PackageIterator.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/utils/Request.kt
- src/backend/analyst/biz-analyst/src/test/kotlin/com/tencent/bkrepo/analyst/utils/RequestTest.kt
- src/backend/repository/api-repository/src/main/kotlin/com/tencent/bkrepo/repository/api/NodeClient.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/controller/service/NodeController.kt
> feat: 优化遍历待扫描制品时不统计制品总数 #898

- src/backend/npm/biz-npm/src/main/kotlin/com/tencent/bkrepo/npm/model/metadata/NpmVersionMetadata.kt
- src/backend/npm/biz-npm/src/main/kotlin/com/tencent/bkrepo/npm/service/impl/NpmWebServiceImpl.kt
> bug: NPM解析早期格式的依赖项时报错 #895

- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/node/impl/NodeBaseService.kt
> fix: 修复未更新所有子节点最后访问时间，指定更新操作使用的索引 #966

- src/frontend/devops-repository/src/views/preview/scanTask.vue
1. feat: 优化制品分析报告详情页面入口交互;
2. fix: 制品分析报告详情页面预览时筛选按钮初始化生效问题处理
> feat: 优化制品分析报告详情页面入口交互 #949

- docs/apidoc/scanner/scan.md
- src/backend/analyst/api-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/pojo/LeakType.kt
- src/backend/analyst/api-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/pojo/ScanTriggerType.kt
- src/backend/analyst/api-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/pojo/response/ScanPlanInfo.kt
- src/backend/analyst/api-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/pojo/response/SubtaskResultOverview.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/controller/user/UserScanController.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/statemachine/task/action/PendingAction.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/utils/Converter.kt
- src/backend/analyst/biz-analyst/src/main/resources/i18n/messages_en.properties
- src/backend/analyst/biz-analyst/src/main/resources/i18n/messages_zh_CN.properties
- src/backend/analyst/biz-analyst/src/main/resources/i18n/messages_zh_TW.properties
> format: 扫描类型, 漏洞等级文案优化 #943

- src/backend/analyst/api-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/pojo/response/ArtifactPlanRelations.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/controller/user/UserScanPlanController.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/ScanPlanService.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/ScanPlanServiceImpl.kt
> fix: 后端适配前端展示制品分析成功状态 #471

- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/cluster/ArtifactClusterConfiguration.kt
- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/repository/ArtifactContextConfiguration.kt
- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/repository/composite/CompositeRepository.kt
- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/repository/context/ArtifactContextHolder.kt
- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/repository/context/ArtifactDownloadContext.kt
- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/repository/core/AbstractArtifactRepository.kt
- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/repository/redirect/CosRedirectService.kt
- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/repository/redirect/DownloadRedirectManager.kt
- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/repository/redirect/DownloadRedirectService.kt
- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/repository/redirect/DownloadRedirectSettings.kt
- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/repository/redirect/EdgeNodeRedirectService.kt
- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/repository/redirect/RedirectTo.kt
- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/repository/virtual/VirtualRepository.kt
- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/resolve/response/DefaultArtifactResourceWriter.kt
- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/util/http/HttpHeaderUtils.kt
- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/StorageProperties.kt
- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/config/RedirectProperties.kt
- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/config/ResponseProperties.kt
- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/innercos/client/ClientConfig.kt
- src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/artifact/GenericLocalRepository.kt
- src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/artifact/GenericRemoteRepository.kt
- src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/service/DownloadService.kt
- src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/service/TemporaryAccessService.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/config/CommonLocalRepository.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/config/CommonRemoteRepository.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/file/impl/ListViewServiceImpl.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/file/impl/ShareServiceImpl.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/file/impl/center/CommitEdgeCenterShareServiceImpl.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/file/impl/edge/EdgeShareServiceImpl.kt
> feat: 支持重定向下载请求到COS #528

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/configuration/ScannerProperties.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/TemporaryScanTokenServiceImpl.kt
> feat: 支持配置扫描任务使用的临时下载链接可用次数与超时时间 #1032

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/event/listener/ScanTaskStatusChangedEventListener.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/statemachine/task/action/PendingAction.kt
- src/backend/common/common-notify/notify-service/src/main/kotlin/com/tencent/bkrepo/common/notify/client/weworkbot/WeworkBotClient.kt
> feat: 支持设置制品分析结果通知人 #677

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/metrics/ScannerMetrics.kt
> fix: 修复导出扫描速度报错 #1048

- src/backend/analyst/api-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/pojo/SubScanTask.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/TemporaryScanTokenServiceImpl.kt
> feat: 支持在创建扫描任务临时下载链接时使用任务元数据中的文件名 #1044

- src/frontend/devops-repository/src/store/actions/permission.js
- src/frontend/devops-repository/src/utils/privacy.js
- src/frontend/devops-repository/src/views/nodeManage/index.vue
- src/frontend/devops-repository/src/views/userCenter/index.vue
- src/frontend/devops-repository/src/views/userCenter/userRelated.vue
- src/frontend/devops-repository/src/views/userManage/user.vue
1、关联团队用户右上角输入框现需移除
2、创建节点界面，udp端口当触发第一次点击后移动，会呈现提醒
3、邮箱、手机号隐私展示
> bug:前端已知问题优化 #1041

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dao/SubScanTaskDao.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/statemachine/subtask/action/DispatchFailedAction.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/statemachine/subtask/action/ExecuteSubtaskAction.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/statemachine/subtask/action/PullSubtaskAction.kt
> feat: 修复无限拉取任务错误 #1152

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dispatcher/KubernetesDeploymentDispatcher.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dispatcher/SubtaskDispatcherFactory.kt
> feat: 增加制品分析Deployment创建删除并发控制 #1040

- src/backend/ddc/biz-ddc/src/main/kotlin/com/tencent/bkrepo/ddc/artifact/repository/DdcLocalRepository.kt
- src/backend/ddc/biz-ddc/src/main/kotlin/com/tencent/bkrepo/ddc/service/ReferenceArtifactService.kt
- src/backend/ddc/biz-ddc/src/main/kotlin/com/tencent/bkrepo/ddc/service/ReferenceService.kt
> bug: 修复DDC finalize ref时仓库类型转换错误 #1161

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dispatcher/KubernetesDeploymentDispatcher.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/statemachine/task/action/PendingAction.kt
> feat: 忽略删除分析任务deployment时候404错误 #1172

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dispatcher/KubernetesDeploymentDispatcher.kt
> feat: 忽略扩缩容分析任务Deployment时409错误 #1172

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/TemporaryScanTokenServiceImpl.kt
> bug: 修复扫描镜像时查询layer对应的node导致数据库CPU负载高 #1191

- src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/interceptor/devx/DevxSrcIpInterceptor.kt
- src/backend/svn/biz-svn/src/main/kotlin/com/tencent/bkrepo/svn/interceptor/DevxSrcIpInterceptor.kt
- src/backend/svn/biz-svn/src/main/kotlin/com/tencent/bkrepo/svn/interceptor/ProxyInterceptor.kt
- src/backend/svn/biz-svn/src/main/kotlin/com/tencent/bkrepo/svn/utils/SvnProxyHelper.kt
> feat: 修复SVN代理仓库OPTIONS请求未进入代理拦截器 #1196

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/statemachine/TaskStateMachineConfiguration.kt
> bug: 修复PULL状态的分析任务未正常超时 #1227

- src/backend/svn/biz-svn/src/main/kotlin/com/tencent/bkrepo/svn/interceptor/ChangeAncestorProxyHandler.kt
- src/backend/svn/biz-svn/src/test/kotlin/com/tencent/bkrepo/svn/interceptor/ChangeAncestorFilterTest.kt
- src/backend/svn/biz-svn/src/test/resources/testdata/test.xml
> bug: 修复SVN代码拉取OOM #1234

- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/config/RepositoryProperties.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/repo/impl/RepositoryServiceImpl.kt
> feat: 创建仓库时自动生成SVN PROXY地址 #1258

- src/backend/ddc/biz-ddc/src/main/kotlin/com/tencent/bkrepo/ddc/artifact/repository/DdcLocalRepository.kt
- src/backend/ddc/biz-ddc/src/main/kotlin/com/tencent/bkrepo/ddc/metrics/DdcMeterBinder.kt
> feat: 增加DDC监控数据导出 #1099

- src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/interceptor/devx/DevxProperties.kt
- src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/interceptor/devx/DevxSrcIpInterceptor.kt
> feat: 支持配置svn/git proxy白名单ip #1278

- src/backend/svn/biz-svn/src/main/kotlin/com/tencent/bkrepo/svn/interceptor/ChangeAncestorProxyHandler.kt
> bug: 修复SVN  PROXY合并分支失败 #1283

- src/backend/repository/api-repository/src/main/kotlin/com/tencent/bkrepo/repository/pojo/project/ProjectCreateRequest.kt
- src/backend/repository/api-repository/src/main/kotlin/com/tencent/bkrepo/repository/pojo/project/ProjectInfo.kt
- src/backend/repository/api-repository/src/main/kotlin/com/tencent/bkrepo/repository/pojo/project/ProjectMetadata.kt
- src/backend/repository/api-repository/src/main/kotlin/com/tencent/bkrepo/repository/pojo/project/ProjectUpdateRequest.kt
- src/backend/repository/api-repository/src/main/kotlin/com/tencent/bkrepo/repository/pojo/project/UserProjectCreateRequest.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/controller/user/UserProjectController.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/model/TProject.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/repo/impl/ProjectServiceImpl.kt
- src/backend/repository/biz-repository/src/test/kotlin/com/tencent/bkrepo/repository/service/ProjectServiceTest.kt
(cherry picked from commit 3e51c06406c64cf58369a31a7fe3ffc07135649b)
1. #1055
> feat: 增加项目元数据字段 #1055

- src/backend/ddc/biz-ddc/src/main/kotlin/com/tencent/bkrepo/ddc/artifact/repository/DdcLocalRepository.kt
> fix: 修复X-Jupiter-InlinePayloadHash返回错误 #1270

- src/backend/ddc/biz-ddc/src/main/kotlin/com/tencent/bkrepo/ddc/repository/BlobRepository.kt
- src/backend/ddc/biz-ddc/src/main/kotlin/com/tencent/bkrepo/ddc/repository/RefBaseRepository.kt
- src/backend/ddc/biz-ddc/src/main/kotlin/com/tencent/bkrepo/ddc/service/BlobService.kt
- src/backend/ddc/biz-ddc/src/main/kotlin/com/tencent/bkrepo/ddc/service/ReferenceService.kt
> fix: 调整创建DDC ref与blob时replace操作为insert #1289

- src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/SecurityAutoConfiguration.kt
- src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/interceptor/devx/ApiAuth.kt
- src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/interceptor/devx/DevXAccessInterceptor.kt
- src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/interceptor/devx/DevXProperties.kt
- src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/interceptor/devx/DevXWorkSpace.kt
- src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/interceptor/devx/DevxProperties.kt
- src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/interceptor/devx/QueryResponse.kt
- src/backend/fs/boot-fs-server/src/main/kotlin/com/tencent/bkrepo/fs/server/config/BeanConfiguration.kt
- src/backend/fs/boot-fs-server/src/main/kotlin/com/tencent/bkrepo/fs/server/config/RouteConfiguration.kt
- src/backend/fs/boot-fs-server/src/main/kotlin/com/tencent/bkrepo/fs/server/filter/DevXAccessFilter.kt
- src/backend/svn/biz-svn/src/main/kotlin/com/tencent/bkrepo/svn/config/SvnConfiguration.kt
- src/backend/svn/biz-svn/src/main/kotlin/com/tencent/bkrepo/svn/interceptor/SvnDevXAccessInterceptor.kt
> feat: 支持FSServer限制DexX用户访问 #1335

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dispatcher/KubernetesDeploymentDispatcher.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dispatcher/KubernetesDispatcher.kt
> fix: 增加K8S接口调用Kind参数 #1350

- src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/SecurityAutoConfiguration.kt
- src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/interceptor/devx/DevXProperties.kt
- src/backend/fs/boot-fs-server/src/main/kotlin/com/tencent/bkrepo/fs/server/filter/DevXAccessFilter.kt
> feat: 支持DevX拦截器配置包含与忽略的接口 #1335

- src/backend/auth/biz-auth/build.gradle.kts
- src/backend/fs/boot-fs-server/build.gradle.kts
> bug: 添加micrometer-prometheus到auth、fs-server服务 #1385

- src/backend/common/common-query/query-mongo/src/main/kotlin/com/tencent/bkrepo/common/query/builder/MongoQueryInterpreter.kt
- src/backend/common/common-query/query-mongo/src/main/kotlin/com/tencent/bkrepo/common/query/interceptor/QueryContext.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/search/common/CommonQueryContext.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/search/common/CommonQueryInterpreter.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/search/common/RepoNameRuleInterceptor.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/search/node/NodeQueryContext.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/search/node/NodeQueryInterpreter.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/search/packages/PackageQueryContext.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/search/packages/PackageSearchInterpreter.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/search/software/packages/SoftwarePackageSearchInterpreter.kt
> bug: 调整NodeSearch接口权限校验 #1356

- src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/interceptor/devx/DevXAccessInterceptor.kt
- src/backend/fs/boot-fs-server/src/main/kotlin/com/tencent/bkrepo/fs/server/filter/DevXAccessFilter.kt
> feat: 支持配置DevX白名单网段 #1392

- src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/interceptor/devx/DevXAccessInterceptor.kt
- src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/interceptor/devx/DevXWorkSpace.kt
- src/backend/fs/boot-fs-server/src/main/kotlin/com/tencent/bkrepo/fs/server/filter/DevXAccessFilter.kt
> bug: 修复DevX InnerIp为null导致的反序列化失败 #1398

- src/backend/fs/boot-fs-server/src/main/kotlin/com/tencent/bkrepo/fs/server/filter/DevXAccessFilter.kt
> bug: 修复WebClient PrematureCloseException #1373

- src/backend/common/common-api/src/main/kotlin/com/tencent/bkrepo/common/api/constant/MediaTypes.kt
- src/backend/common/common-service/src/main/kotlin/com/tencent/bkrepo/common/service/exception/AbstractExceptionHandler.kt
> bug: 修复NodeNotFoundException打印error日志  #1423

- src/backend/fs/boot-fs-server/src/main/kotlin/com/tencent/bkrepo/fs/server/utils/DevxWorkspaceUtils.kt
> bug: 优化DevX缓存刷新操作 #1430

- src/backend/common/common-api/src/main/kotlin/com/tencent/bkrepo/common/api/constant/MediaTypes.kt
- src/backend/common/common-service/src/main/kotlin/com/tencent/bkrepo/common/service/exception/AbstractExceptionHandler.kt
> bug: 修复accept header为null导致的空指针错误 #1423

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/utils/K8SHelper.kt
> bug: 修复创建k8s Secret时缺少kind参数 #1444

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/configuration/ScannerConfiguration.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/ProjectUsageStatisticsServiceImpl.kt
- src/backend/common/common-api/src/main/kotlin/com/tencent/bkrepo/common/api/constant/Constants.kt
- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/event/listener/ArtifactTransferListener.kt
- src/backend/common/common-operate/operate-api/src/main/kotlin/com/tencent/bkrepo/common/operate/api/ProjectUsageStatisticsService.kt
- src/backend/common/common-operate/operate-api/src/main/kotlin/com/tencent/bkrepo/common/operate/api/pojo/ProjectUsageStatistics.kt
- src/backend/common/common-operate/operate-api/src/main/kotlin/com/tencent/bkrepo/common/operate/api/pojo/ProjectUsageStatisticsListOption.kt
- src/backend/common/common-operate/operate-service/src/main/kotlin/com/tencent/bkrepo/common/operate/service/OperateAutoConfiguration.kt
- src/backend/common/common-operate/operate-service/src/main/kotlin/com/tencent/bkrepo/common/operate/service/config/ProjectUsageStatisticsProperties.kt
- src/backend/common/common-operate/operate-service/src/main/kotlin/com/tencent/bkrepo/common/operate/service/dao/ProjectUsageStatisticsDao.kt
- src/backend/common/common-operate/operate-service/src/main/kotlin/com/tencent/bkrepo/common/operate/service/interceptor/ProjectUsageStatisticsInterceptor.kt
- src/backend/common/common-operate/operate-service/src/main/kotlin/com/tencent/bkrepo/common/operate/service/model/TProjectUsageStatistics.kt
- src/backend/common/common-operate/operate-service/src/main/kotlin/com/tencent/bkrepo/common/operate/service/service/ProjectUsageStatisticsServiceImpl.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/ProjectUsageStatisticsCleanupJob.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/config/properties/ProjectUsageStatisticsCleanupJobProperties.kt
- src/backend/opdata/biz-opdata/src/main/kotlin/com/tencent/bkrepo/opdata/controller/ProjectController.kt
- src/backend/repository/api-repository/src/main/kotlin/com/tencent/bkrepo/repository/api/ProjectUsageStatisticsClient.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/controller/service/ProjectUsageStatisticsController.kt
> feat: 增加项目流量使用情况统计 #1311

- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/repository/remote/RemoteRepository.kt
- src/backend/common/common-service/src/main/kotlin/com/tencent/bkrepo/common/service/util/okhttp/PlatformAuthInterceptor.kt
- src/backend/generic/api-generic/src/main/kotlin/com/tencent/bkrepo/generic/constant/GenericMessageCode.kt
- src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/artifact/GenericLocalRepository.kt
- src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/artifact/GenericRemoteRepository.kt
- src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/artifact/Utils.kt
- src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/artifact/context/GenericArtifactSearchContext.kt
- src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/config/GenericProperties.kt
- src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/config/PlatformAuthProperties.kt
- src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/controller/GenericController.kt
- src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/service/DownloadService.kt
- src/backend/generic/biz-generic/src/main/resources/i18n/messages_en.properties
- src/backend/generic/biz-generic/src/main/resources/i18n/messages_zh_CN.properties
- src/backend/generic/biz-generic/src/main/resources/i18n/messages_zh_TW.properties
> feat: 支持Generic Remote仓库下载 #1400

- src/frontend/devops-repository/src/store/actions/repoGeneric.js
- src/frontend/devops-repository/src/views/repoGeneric/genericDetail.vue
- src/frontend/devops-repository/src/views/repoGeneric/index.vue
> feat: 支持展示远程Generic仓库制品 #1400

- src/backend/analyst/api-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/message/ScannerMessageCode.kt
- src/backend/analyst/api-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/pojo/ScanTask.kt
- src/backend/analyst/api-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/pojo/request/GlobalScanRequest.kt
- src/backend/analyst/api-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/pojo/request/ScanTaskQuery.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/component/ScannerPermissionCheckHandler.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/configuration/ScannerProperties.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/controller/user/UserScanController.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dao/ScanTaskDao.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dao/SubScanTaskDao.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/model/TScanTask.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/ProjectScanConfigurationService.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/ScanService.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/ProjectScanConfigurationServiceImpl.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/ScanServiceImpl.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/ScanTaskServiceImpl.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/statemachine/iterator/NodeIterator.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/statemachine/task/action/PendingAction.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/statemachine/task/action/SubmittingAction.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/utils/Converter.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/utils/RuleConverter.kt
- src/backend/analyst/biz-analyst/src/main/resources/i18n/messages_en.properties
- src/backend/analyst/biz-analyst/src/main/resources/i18n/messages_zh_CN.properties
- src/backend/analyst/biz-analyst/src/main/resources/i18n/messages_zh_TW.properties
- src/backend/repository/api-repository/src/main/kotlin/com/tencent/bkrepo/repository/pojo/project/ProjectRangeQueryRequest.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/repo/impl/ProjectServiceImpl.kt
- src/backend/repository/biz-repository/src/test/kotlin/com/tencent/bkrepo/repository/service/ProjectServiceTest.kt
> feat: 支持触发全局扫描任务 #877

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dao/SubScanTaskDao.kt
> fix: 设置系统级别扫描任务不算入项目配额 #1461

- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/project/BkciProjectMetadataSyncJob.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/project/BkciProjectMetadataSyncJobProperties.kt
- src/backend/opdata/api-opdata/src/main/kotlin/com/tencent/bkrepo/opdata/pojo/ProjectMetrics.kt
- src/backend/opdata/biz-opdata/src/main/kotlin/com/tencent/bkrepo/opdata/service/ProjectMetricsService.kt
- src/backend/repository/api-repository/src/main/kotlin/com/tencent/bkrepo/repository/pojo/project/ProjectMetadata.kt
> feat: 增加同步蓝盾项目元数据定时任务 #1543

- src/backend/analyst/api-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/pojo/response/ArtifactVulnerabilityInfo.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/component/manager/standard/StandardConverter.kt
- src/frontend/devops-repository/src/views/repoScan/artiReport/leak.vue
> feat: 展示制品所有存在风险组件的路径 #1528

- src/backend/npm/biz-npm/src/main/kotlin/com/tencent/bkrepo/npm/utils/NpmUtils.kt
issue:
1. #1140
在请求package.json元数据时，如果不添加X-BKREPO-NPM-PREFIX请求头且npm.tarball.prefix、npm.domain配置项不为空，返回的tgz包下载地址缺少projectId和repoName，导致无法从npm仓库拉取制品。
> fix: 部分情况无法从npm仓库拉取制品 #1140

- src/backend/job/api-job/src/main/kotlin/com/tencent/bkrepo/job/api/JobClient.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/base/ActiveProjectService.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/controller/service/JobController.kt
- src/backend/opdata/biz-opdata/src/main/kotlin/com/tencent/bkrepo/opdata/config/OpProperties.kt
- src/backend/opdata/biz-opdata/src/main/kotlin/com/tencent/bkrepo/opdata/controller/BkBaseExportController.kt
- src/backend/opdata/biz-opdata/src/main/kotlin/com/tencent/bkrepo/opdata/controller/ProjectController.kt
> feat: 支持bkbase拉取活跃用户与项目 #1551

- src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/artifact/GenericRemoteRepository.kt
- src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/artifact/remote/AsyncRemoteArtifactCacheWriter.kt
- src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/artifact/remote/RemoteArtifactCacheWriter.kt
> feat: 支持缓存远程制品的同时缓存远程节点元数据 #1590

- src/backend/common/common-artifact/artifact-api/src/main/kotlin/com/tencent/bkrepo/common/artifact/constant/ArtifactConstants.kt
- src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/interceptor/devx/DevXProperties.kt
- src/backend/repository/api-repository/src/main/kotlin/com/tencent/bkrepo/repository/pojo/webhook/BkCiDevXEnabledPayload.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/config/RepositoryProperties.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/controller/user/UserBkCiWebhookController.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/webhook/BkciWebhookListener.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/webhook/DevXBkciWebhookListener.kt
> feat: 增加Bkci DevX开启事件监听器 #1582

- src/backend/fs/boot-fs-server/src/main/kotlin/com/tencent/bkrepo/fs/server/NodeExtensions.kt
- src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/artifact/GenericLocalRepository.kt
- src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/artifact/GenericRemoteRepository.kt
- src/backend/repository/api-repository/src/main/kotlin/com/tencent/bkrepo/repository/api/PipelineNodeClient.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/controller/service/PipelineNodeController.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/controller/user/UserPipelineController.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/node/PipelineNodeService.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/node/impl/PipelineNodeServiceImpl.kt
- src/frontend/devops-repository/src/store/actions/repoGeneric.js
> feat: 对齐本地与远程流水线仓库权限 #1620

- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/repository/context/ArtifactSearchContext.kt
- src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/artifact/GenericLocalRepository.kt
- src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/artifact/GenericRemoteRepository.kt
- src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/artifact/Utils.kt
- src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/artifact/context/GenericArtifactSearchContext.kt
- src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/artifact/remote/AsyncRemoteArtifactCacheWriter.kt
- src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/artifact/remote/RemoteArtifactCacheWriter.kt
- src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/service/DownloadService.kt
> fix: 修复代理流水线仓库时未展示构建号 #1654

- src/backend/opdata/biz-opdata/src/main/kotlin/com/tencent/bkrepo/opdata/model/GcInfoModel.kt
> fix: 限制GcInfoModel线程池大小 #1709

- src/backend/common/common-operate/operate-service/src/main/kotlin/com/tencent/bkrepo/common/operate/service/service/ProjectUsageStatisticsServiceImpl.kt
- src/backend/opdata/api-opdata/src/main/kotlin/com/tencent/bkrepo/opdata/pojo/enums/Metrics.kt
- src/backend/opdata/biz-opdata/src/main/kotlin/com/tencent/bkrepo/opdata/handler/impl/ProjectTrafficHandler.kt
> feat: 增加项目流量数据Grafana报表 #1698

- src/backend/opdata/biz-opdata/src/main/kotlin/com/tencent/bkrepo/opdata/handler/impl/ProjectTrafficHandler.kt
> feat: 调整项目流量数据grafana报表为展示数字 #1698

- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/ExpiredCacheFileCleanupJob.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/base/BatchJob.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/config/JobConfig.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/config/JobProperties.kt
> feat: 支持Job服务配置定时任务与宿主机的亲和性 #1723

- src/backend/common/common-query/query-api/src/main/kotlin/com/tencent/bkrepo/common/query/enums/OperationType.kt
- src/backend/common/common-query/query-api/src/main/kotlin/com/tencent/bkrepo/common/query/matcher/RuleMatcher.kt
- src/backend/common/common-query/query-api/src/main/kotlin/com/tencent/bkrepo/common/query/matcher/impl/RegexIMatcher.kt
- src/backend/common/common-query/query-api/src/test/kotlin/com/tencent/bkrepo/common/query/matcher/RuleMatcherTest.kt
- src/backend/common/common-query/query-mongo/src/main/kotlin/com/tencent/bkrepo/common/query/builder/MongoQueryInterpreter.kt
- src/backend/common/common-query/query-mongo/src/main/kotlin/com/tencent/bkrepo/common/query/handler/impl/RegexIHandler.kt
1. #1740
1. pypi仓库的规范化需要使用这种查询方式。
> feat: 添加大小写不敏感的Regex查询方式 #1740

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/ProjectUsageStatisticsServiceImpl.kt
- src/backend/common/common-operate/operate-api/src/main/kotlin/com/tencent/bkrepo/common/operate/api/ProjectUsageStatisticsService.kt
- src/backend/common/common-operate/operate-service/src/main/kotlin/com/tencent/bkrepo/common/operate/service/dao/ProjectUsageStatisticsDao.kt
- src/backend/common/common-operate/operate-service/src/main/kotlin/com/tencent/bkrepo/common/operate/service/service/ProjectUsageStatisticsServiceImpl.kt
- src/backend/opdata/biz-opdata/src/main/kotlin/com/tencent/bkrepo/opdata/handler/impl/ProjectTrafficHandler.kt
- src/backend/opdata/biz-opdata/src/main/kotlin/com/tencent/bkrepo/opdata/service/ProjectMetricsService.kt
> feat: 支持导出一段时间内的项目流量使用数据 #1744

- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/webhook/DevXBkciWebhookListener.kt
> feat: 忽略DevX创建远程仓库冲突错误 #1682

- src/backend/pypi/api-pypi/src/main/kotlin/com/tencent/bkrepo/pypi/constants/Constant.kt
- src/backend/pypi/api-pypi/src/main/kotlin/com/tencent/bkrepo/pypi/constants/PypiQueryType.kt
- src/backend/pypi/biz-pypi/src/main/kotlin/com/tencent/bkrepo/pypi/artifact/repository/PypiLocalRepository.kt
- src/backend/pypi/biz-pypi/src/main/kotlin/com/tencent/bkrepo/pypi/artifact/repository/PypiRemoteRepository.kt
- src/backend/pypi/biz-pypi/src/main/kotlin/com/tencent/bkrepo/pypi/service/PypiService.kt
- src/backend/pypi/biz-pypi/src/main/kotlin/com/tencent/bkrepo/pypi/service/PypiWebService.kt
- src/backend/pypi/biz-pypi/src/main/kotlin/com/tencent/bkrepo/pypi/util/UrlUtils.kt
> refactor: pypi query结构调整 #1749

- src/frontend/devops-op/package.json
- src/frontend/devops-op/src/utils/date.js
- src/frontend/devops-op/src/views/job/index.vue
任务名称输入，动态匹配（忽略大小写）。有2列隐藏列（上次耗时和下次启动时间），可以选择展出。是否运行，点击标题筛选。上次耗时自动转换，超过特定时间会转换（最大到天）
> feat:优化op系统任务管理展示 #1813

- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/innercos/InnerCosFileStorage.kt
> feat: 增加cos检查文件是否存在请求失败日志 #1858

- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/cache/indexer/IndexerCustomizer.kt
- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/cache/indexer/StorageCacheIndexConfiguration.kt
- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/cache/indexer/StorageCacheIndexer.kt
- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/cache/indexer/StorageCacheIndexerFactory.kt
- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/cache/indexer/StorageCacheIndexerManager.kt
- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/cache/indexer/listener/EldestRemovedListener.kt
- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/cache/indexer/listener/StorageEldestRemovedListener.kt
- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/cache/indexer/listener/UpdatableEldestRemovedListener.kt
- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/cache/indexer/redis/RedisCacheIndexer.kt
- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/cache/indexer/redis/RedisLRUCacheIndexer.kt
- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/cache/indexer/redis/RedisSLRUCacheIndexer.kt
- src/backend/common/common-storage/storage-service/src/test/kotlin/com/tencent/bkrepo/common/storage/core/cache/indexer/redis/RedisCacheIndexerTest.kt
- src/backend/common/common-storage/storage-service/src/test/kotlin/com/tencent/bkrepo/common/storage/core/cache/indexer/redis/RedisLRUCacheIndexerTest.kt
- src/backend/common/common-storage/storage-service/src/test/kotlin/com/tencent/bkrepo/common/storage/core/cache/indexer/redis/RedisSLRUCacheIndexerTest.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/file/BasedRepositoryFileExpireResolver.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/ExpiredCacheFileCleanupJob.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/StorageCacheIndexEvictJob.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/StorageCacheIndexJob.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/StorageCacheIndexSyncJob.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/StorageCacheIndexerCustomizer.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/config/properties/StorageCacheIndexEvictJobProperties.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/config/properties/StorageCacheIndexSyncJobProperties.kt
> feat: 支持在job服务中进行缓存索引淘汰并保留指定缓存文件 #1889

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dispatcher/DockerDispatcher.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dispatcher/KubernetesDeploymentDispatcher.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dispatcher/KubernetesDispatcher.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dispatcher/SubtaskDispatcherFactory.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dispatcher/SubtaskPushDispatcher.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/statemachine/subtask/action/RetryAction.kt
- src/backend/common/common-redis/src/main/kotlin/com/tencent/bkrepo/common/redis/RedisLock.kt
> bug: 修复分析任务Job删除延迟导致任务分发重试失败及错误输出告警 #1805

- src/backend/analyst/api-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/pojo/report/Component.kt
> feat: 去重分析结果上报的组件漏洞 #1867

- src/backend/fs/api-fs-server/src/main/kotlin/com/tencent/bkrepo/fs/server/api/FsClientClient.kt
- src/backend/fs/api-fs-server/src/main/kotlin/com/tencent/bkrepo/fs/server/pojo/DailyClientDetail.kt
- src/backend/fs/api-fs-server/src/main/kotlin/com/tencent/bkrepo/fs/server/pojo/DailyClientListRequest.kt
- src/backend/fs/boot-fs-server/src/main/kotlin/com/tencent/bkrepo/fs/server/config/RouteConfiguration.kt
- src/backend/fs/boot-fs-server/src/main/kotlin/com/tencent/bkrepo/fs/server/handler/ClientHandler.kt
- src/backend/fs/boot-fs-server/src/main/kotlin/com/tencent/bkrepo/fs/server/model/TDailyClient.kt
- src/backend/fs/boot-fs-server/src/main/kotlin/com/tencent/bkrepo/fs/server/repository/DailyClientRepository.kt
- src/backend/fs/boot-fs-server/src/main/kotlin/com/tencent/bkrepo/fs/server/service/ClientService.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/other/FsClientOfflineJob.kt
- src/backend/opdata/biz-opdata/src/main/kotlin/com/tencent/bkrepo/opdata/controller/FsClientController.kt
- src/frontend/devops-op/src/api/fileSystem.js
- src/frontend/devops-op/src/router/index.js
- src/frontend/devops-op/src/views/node/FileSystemRecord.vue
- src/frontend/devops-op/src/views/node/components/FileSystemStatusRecordDialog.vue
管理页新增上下线记录，可按时间查询。新增客户端在线情况统计。
> feat:driver客户端管理支持按项目每日统计 #1842

- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/base/BatchJob.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/ExpiredCacheFileCleanupJob.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/clean/FileReferenceCleanupJob.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/config/JobProperties.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/config/properties/BatchJobProperties.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/config/properties/FileReferenceCleanupJobProperties.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/batch/FileReferenceCleanupJobTest.kt
> feat: 清理引用数为负的FileReference，支持忽略不清理指定存储 #1902

- src/backend/job/api-job/src/main/kotlin/com/tencent/bkrepo/job/pojo/JobDetail.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/base/BatchJob.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/service/SystemJobService.kt
- src/frontend/devops-op/src/views/job/index.vue
[https://github.com/TencentBlueKing/bk-repo/pull/1901](url)
> feat:op任务管理修改错误 #1876

- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/metrics/StorageCacheMetrics.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/metrics/StorageCacheMetricsTest.kt
> fix: 修复缓存监控数据错误 #1978

- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/util/PathExtensions.kt
> feat: 调整Stale file handle异常日志等级 #1976

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dispatcher/KubernetesDispatcher.kt
> feat: 调整制品分析可执行任务数计算方式 #155

- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/dao/MigrateFailedNodeDao.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/dao/MigrateRepoStorageTaskDao.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/executor/BaseTaskExecutor.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/executor/MigrateExecutor.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/executor/MigrateFailedNodeExecutor.kt
> fix: 修复先写后读mongo从库导致任务状态不一致 #2050

- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/clean/FileReferenceCleanupJob.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/other/MigrateRepoStorageJob.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/utils/NodeCommonUtils.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/exception/RepoMigratingException.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/migrate/executor/MigrateExecutorTest.kt
> fix: 修复迁移任务job每次只触发一个任务 #2058

- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/MigrateRepoStorageService.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/dao/MigrateRepoStorageTaskDao.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/migrate/MigrateRepoStorageServiceTest.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/migrate/executor/FinishExecutorTest.kt
> fix: 设置PENDING状态的任务不属于迁移中状态 #2061

- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/MigrateRepoStorageService.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/dao/MigrateRepoStorageTaskDao.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/migrate/MigrateRepoStorageServiceTest.kt
> fix: 设置任务状态回滚到PENDING也判断为迁移中 #2061

- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/dao/MigrateRepoStorageTaskDao.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/executor/MigrateExecutor.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/utils/NodeIterator.kt
> fix: 强制从主库查询迁移任务 #2068

- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/MigrateRepoStorageService.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/dao/MigrateRepoStorageTaskDao.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/migrate/MigrateRepoStorageServiceTest.kt
> fix: 遍历所有可执行状态的迁移任务 #2068

- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/repository/redirect/LinkNodeRedirectService.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/migrate/executor/MigrateExecutorTest.kt
> fix: 修复文件路径包含中文时软链接节点下载重定向链接错误 #2074

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dispatcher/KubernetesDispatcher.kt
> fix: 修复清理分析任务job时404错误 #2072

- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/util/PathExtensions.kt
> fix: 修复删除目录时未正常捕获Stale file handle异常 #1976

- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/metrics/ArtifactCacheMetrics.kt
> fix: 忽略统计缓存访问数据时出现的NoSuchFileException #2081

- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/executor/BaseTaskExecutor.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/utils/NodeIterator.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/migrate/executor/ExecutorBaseTest.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/migrate/executor/MigrateExecutorTest.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/migrate/utils/NodeIteratorTest.kt
> feat: 设置迁移FakeNode时抛出异常 #2075

- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/innercos/http/CosHttpClient.kt
- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/innercos/http/HttpResponseHandler.kt
- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/innercos/response/handler/GetObjectResponseHandler.kt
> fix: 修复okhttp连接泄漏 #2093

- src/backend/common/common-mongo/src/main/kotlin/com/tencent/bkrepo/common/mongo/constant/Constants.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/utils/NodeIterator.kt
> fix: 修复遍历待迁移node过慢，强制使用_id_索引 #2096

- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/utils/NodeIterator.kt
> fix: 修复统计待迁移node总数过慢 #2096

- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/utils/NodeIterator.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/migrate/utils/NodeIteratorTest.kt
> fix: 优化查询第一页待迁移node速度过慢 #2100

- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/controller/user/UserMigrateRepoStorageController.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/MigrateFailedNodeService.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/MigrateRepoStorageService.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/dao/ArchiveMigrateFailedNodeDao.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/dao/MigrateFailedNodeDao.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/dao/MigrateRepoStorageTaskDao.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/executor/BaseTaskExecutor.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/executor/CorrectExecutor.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/executor/MigrateExecutor.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/executor/handler/DefaultMigrateFailedHandler.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/executor/handler/MigrateFailedHandler.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/model/TArchiveMigrateFailedNode.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/pojo/Node.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/strategy/FileNotFoundAutoFixStrategy.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/strategy/MigrateFailedNodeAutoFixStrategy.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/migrate/MigrateFailedNodeServiceTest.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/migrate/executor/CorrectExecutorTest.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/migrate/executor/ExecutorBaseTest.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/migrate/executor/MigrateExecutorTest.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/migrate/strategy/FileNotFoundAutoFixStrategyTest.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/migrate/utils/MigrateTestUtils.kt
> feat: 提供处理迁移失败Node接口 #2063

- src/backend/buildSrc/src/main/kotlin/Versions.kt
- src/backend/pypi/api-pypi/src/main/kotlin/com/tencent/bkrepo/pypi/artifact/PypiArtifactInfo.kt
- src/backend/pypi/api-pypi/src/main/kotlin/com/tencent/bkrepo/pypi/artifact/PypiSimpleArtifactInfo.kt
- src/backend/pypi/api-pypi/src/main/kotlin/com/tencent/bkrepo/pypi/constants/Constant.kt
- src/backend/pypi/biz-pypi/src/main/kotlin/com/tencent/bkrepo/pypi/artifact/repository/PypiLocalRepository.kt
- src/backend/pypi/biz-pypi/src/main/kotlin/com/tencent/bkrepo/pypi/artifact/repository/PypiRemoteRepository.kt
- src/backend/pypi/biz-pypi/src/main/kotlin/com/tencent/bkrepo/pypi/artifact/resolver/PypiArtifactInfoResolver.kt
- src/backend/pypi/biz-pypi/src/main/kotlin/com/tencent/bkrepo/pypi/artifact/resolver/PypiSimpleArtifactInfoResolver.kt
- src/backend/pypi/biz-pypi/src/main/kotlin/com/tencent/bkrepo/pypi/controller/PypiResourceController.kt
- src/backend/pypi/biz-pypi/src/main/kotlin/com/tencent/bkrepo/pypi/service/PypiService.kt
- src/backend/pypi/biz-pypi/src/main/kotlin/com/tencent/bkrepo/pypi/service/PypiWebService.kt
- src/backend/pypi/biz-pypi/src/main/kotlin/com/tencent/bkrepo/pypi/util/HtmlUtils.kt
- src/backend/pypi/biz-pypi/src/main/kotlin/com/tencent/bkrepo/pypi/util/XmlUtils.kt
issue
1. #1760
描述
1. simple接口检索不到含有特殊字符和大写字母的包
2. simple接口返回格式不符合规范
> fix: pypi本地仓库规范化 #1760

- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/executor/handler/DefaultMigrateFailedHandler.kt
> feat: 修复LoggerFactory类找不到错误 #2063

- src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/service/TemporaryAccessService.kt
> bug: 修复通过临时下载链接下载远程仓库制品时报NPE #2157

- src/backend/common/common-artifact/artifact-cache/src/main/kotlin/com/tencent/bkrepo/common/artifact/cache/dao/ArtifactPreloadPlanDao.kt
- src/backend/common/common-artifact/artifact-cache/src/main/kotlin/com/tencent/bkrepo/common/artifact/cache/service/impl/DefaultPreloadListener.kt
- src/backend/common/common-artifact/artifact-cache/src/main/kotlin/com/tencent/bkrepo/common/artifact/cache/service/impl/DefaultPreloadPlanExecutor.kt
- src/backend/common/common-artifact/artifact-cache/src/test/kotlin/com/tencent/bkrepo/common/artifact/cache/service/impl/ArtifactPreloadBaseServiceTest.kt
- src/backend/common/common-artifact/artifact-cache/src/test/kotlin/com/tencent/bkrepo/common/artifact/cache/service/impl/ArtifactPreloadPlanServiceImplTest.kt
- src/backend/common/common-artifact/artifact-cache/src/test/kotlin/com/tencent/bkrepo/common/artifact/cache/service/impl/DefaultPreloadPlanExecutorTest.kt
> feat: 设置缓存文件存在时预加载仅更新文件mtime #2155

- src/backend/common/common-artifact/artifact-cache/src/main/kotlin/com/tencent/bkrepo/common/artifact/cache/model/TArtifactAccessRecord.kt
- src/backend/common/common-artifact/artifact-cache/src/main/kotlin/com/tencent/bkrepo/common/artifact/cache/service/impl/ArtifactPreloadPlanServiceImpl.kt
- src/backend/common/common-artifact/artifact-cache/src/test/kotlin/com/tencent/bkrepo/common/artifact/cache/service/impl/ArtifactPreloadPlanServiceImplTest.kt
> feat: 调整生成预加载策略时node数量超过限制错误日志级别，取消lastModifiedDate唯一索引限制 #2153

- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/FileBlockSupport.kt
- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/operation/FileBlockOperation.kt
- src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/service/UploadService.kt
> fix: 分块文件列表的文件序号可能不正确 #2173

- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/config/MigrateRepoStorageProperties.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/executor/CorrectExecutor.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/executor/MigrateExecutor.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/executor/MigrateFailedNodeExecutor.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/utils/TransferDataExecutor.kt
> feat: 增加小文件迁移线程池 #2190

- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/config/MigrateRepoStorageProperties.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/utils/TransferDataExecutor.kt
> feat: 修复smallNodeConcurrenCy配置名称错误 #2190

- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/utils/NodeIterator.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/migrate/utils/MigrateTestUtils.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/migrate/utils/NodeIteratorTest.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/model/TNode.kt
> feat: 指定查询首个待迁移节点时使用PATH_IDX索引 #2162

- src/backend/repository/api-repository/src/main/kotlin/com/tencent/bkrepo/repository/pojo/node/NodeListOption.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/search/common/RepoNameRuleInterceptor.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/node/impl/NodeBaseService.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/util/NodeQueryHelper.kt
- src/backend/repository/biz-repository/src/test/kotlin/com/tencent/bkrepo/repository/service/NodeSearchServiceTest.kt
- src/backend/repository/biz-repository/src/test/kotlin/com/tencent/bkrepo/repository/service/NodeServiceTest.kt
> feat: 支持node search与list接口仅展示有权限的路径 #2164

- src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/interceptor/devx/DevXAccessInterceptor.kt
> bug: 设置匿名访问devx时返回401 #2211

- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/search/common/RepoNameRuleInterceptor.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/util/NodeQueryHelper.kt
- src/backend/repository/biz-repository/src/test/kotlin/com/tencent/bkrepo/repository/service/NodeSearchServiceTest.kt
- src/backend/repository/biz-repository/src/test/kotlin/com/tencent/bkrepo/repository/service/NodeServiceTest.kt
> feat: 允许在拥有子文件权限时search与list接口返回父目录node #2164

- src/frontend/devops-repository/src/views/repoConfig/index.vue
> feat: 支持为ddc仓库配置目录权限 #2248

- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/controller/user/UserMigrateRepoStorageController.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/Constant.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/MigrateFailedNodeService.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/dao/MigrateFailedNodeDao.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/executor/MigrateFailedNodeExecutor.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/strategy/FileNotFoundAutoFixStrategy.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/strategy/MigrateFailedNodeFixer.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/migrate/MigrateFailedNodeServiceTest.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/migrate/executor/MigrateFailedNodeExecutorTest.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/migrate/strategy/FileNotFoundAutoFixStrategyTest.kt
> feat: 支持触发所有项目自动修复迁移失败Node #2246

- src/backend/common/common-artifact/artifact-cache/src/main/kotlin/com/tencent/bkrepo/common/artifact/cache/service/impl/ArtifactPreloadPlanServiceImpl.kt
- src/backend/common/common-artifact/artifact-cache/src/main/kotlin/com/tencent/bkrepo/common/artifact/cache/service/impl/DefaultPreloadPlanExecutor.kt
> bug: 修复预加载计划超时失败后未删除记录 #2242

- src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/interceptor/devx/DevXAccessInterceptor.kt
- src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/interceptor/devx/DevXCvmWorkspace.kt
- src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/interceptor/devx/DevXProperties.kt
- src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/interceptor/devx/PageResponse.kt
- src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/interceptor/devx/QueryResponse.kt
- src/backend/fs/boot-fs-server/src/main/kotlin/com/tencent/bkrepo/fs/server/utils/DevxWorkspaceUtils.kt
> feat: 支持获取DevX CVM Workspace #2226

- src/backend/common/common-storage/storage-service/build.gradle.kts
- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/StorageAutoConfiguration.kt
- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/cache/CacheStorageService.kt
- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/cache/indexer/StorageCacheIndexConfiguration.kt
- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/cache/indexer/metrics/StorageCacheIndexerMetrics.kt
- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/filesystem/cleanup/CleanupFileVisitor.kt
- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/filesystem/cleanup/CleanupResult.kt
- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/filesystem/cleanup/CompositeFileExpireResolver.kt
- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/filesystem/cleanup/FileRetainResolver.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/file/BasedRepositoryFileExpireResolver.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/file/ExpireFileResolverConfig.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/ExpiredCacheFileCleanupJob.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/StorageCacheIndexerCustomizer.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/metrics/StorageCacheMetrics.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/metrics/StorageCacheMetricsTest.kt
> feat: 统计保留与淘汰的缓存文件大小及数量 #2240

- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/node/impl/NodeBaseService.kt
> fix: 修复系统用户获取node列表为空 #2271

- src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/interceptor/devx/DevXAccessInterceptor.kt
- src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/interceptor/devx/DevXProperties.kt
- src/backend/fs/boot-fs-server/src/main/kotlin/com/tencent/bkrepo/fs/server/utils/DevxWorkspaceUtils.kt
> fix: 修复获取CVM IP失败 #2226

- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/StorageCacheIndexerCustomizer.kt
> fix: 修复未开启缓存主动淘汰时Job启动失败 #2240

- src/backend/job/api-job/build.gradle.kts
- src/backend/job/api-job/src/main/kotlin/com/tencent/bkrepo/job/pojo/ArchiveRestoreRequest.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/controller/user/ArchiveJobController.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/service/ArchiveJobService.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/service/impl/ArchiveJobServiceImpl.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/model/TNode.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/service/impl/ArchiveJobServiceImplTest.kt
> feat: 支持多种维度取回项目归档的数据 #2219

- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/repository/core/AbstractArtifactRepository.kt
- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/resolve/response/AbstractArtifactResourceHandler.kt
- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/resolve/response/DefaultArtifactResourceWriter.kt
> feat: 支持输出详细下载失败日志 #2326

- src/backend/analysis-executor/biz-analysis-executor/src/main/kotlin/com/tencent/bkrepo/analysis/executor/util/DockerScanHelper.kt
- src/backend/analyst/api-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/pojo/Node.kt
- src/backend/analyst/api-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/pojo/TaskMetadata.kt
- src/backend/analyst/api-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/pojo/execution/KubernetesExecutionClusterProperties.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dispatcher/KubernetesDeploymentDispatcher.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dispatcher/KubernetesDispatcher.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dispatcher/ResourceRequirements.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/statemachine/iterator/NodeFilter.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/statemachine/subtask/action/CreateSubtaskAction.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/statemachine/task/action/SubmittingAction.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/utils/Request.kt
- src/backend/analyst/biz-analyst/src/test/kotlin/com/tencent/bkrepo/analyst/utils/RequestTest.kt
- src/backend/common/common-analysis/src/main/kotlin/com/tencent/bkrepo/common/analysis/pojo/scanner/Scanner.kt
- src/frontend/devops-op/src/views/scan/components/CreateOrUpdateScannerDialog.vue
> feat: 允许不同分析工具个性化配置资源限制 #233

- src/backend/common/common-artifact/artifact-cache/src/main/kotlin/com/tencent/bkrepo/common/artifact/cache/service/impl/ArtifactAccessRecorder.kt
> fix: 修复ArtifactAccessRecordCleanupJob空指针错误 #2332

- src/backend/ddc/biz-ddc/src/main/kotlin/com/tencent/bkrepo/ddc/artifact/repository/DdcLocalRepository.kt
- src/backend/ddc/biz-ddc/src/main/kotlin/com/tencent/bkrepo/ddc/service/ReferenceResolver.kt
- src/backend/ddc/biz-ddc/src/main/kotlin/com/tencent/bkrepo/ddc/service/ReferenceService.kt
> fix: 修复DDC服务读取结束后未关闭文件流导致FD泄漏 #2349

- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/util/ClusterUtils.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/metadata/impl/edge/EdgeMetadataServiceImpl.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/node/impl/edge/EdgeNodeServiceImpl.kt
#2328 增加了ProjectNotFoundException
> feat: Commit-Edge模式兼容独立集群模式 #2298

- src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/interceptor/devx/DevXAccessInterceptor.kt
- src/backend/fs/boot-fs-server/src/main/kotlin/com/tencent/bkrepo/fs/server/filter/DevXAccessFilter.kt
- src/backend/fs/boot-fs-server/src/main/kotlin/com/tencent/bkrepo/fs/server/utils/DevxWorkspaceUtils.kt
> feat: 支持异步刷新devx ip缓存 #2282

- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/clean/DeletedNodeCleanupJob.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/config/properties/DeletedNodeCleanupJobProperties.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/batch/task/clean/DeletedNodeCleanupJobTest.kt
1. #2306 
允许设置异常node保留时间用于保留node记录排查问题，默认保留时间为16天，超过这个时间后将会为node补偿创建一个计数为0的FileReference并删除node
> feat: 支持清理引用不存在的Node #2306

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dispatcher/SubtaskPushDispatcher.kt
> feat: 增加分析任务分发失败日志 #2392

- src/backend/analyst/api-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/pojo/execution/KubernetesExecutionClusterProperties.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dispatcher/CommonUtils.kt
> feat: 支持配置扫描集群client-cert&key #2395

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/configuration/ScannerProperties.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dispatcher/CommonUtils.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dispatcher/DockerDispatcher.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dispatcher/KubernetesDeploymentDispatcher.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dispatcher/KubernetesDispatcher.kt
> feat: 支持扫描器调用制品库接口时进行认证 #2399

- src/frontend/devops-op/src/layout/components/Navbar.vue
- src/frontend/devops-op/src/permission.js
- src/frontend/devops-op/src/store/modules/user.js
- src/frontend/devops-op/src/utils/auth.js
非standalone模式优先使用cookie，cookie取不到使用请求去取用户信息
> bug: 优化op登录（太湖登录情况下，无cookie正常登录） #2441

- src/backend/npm/biz-npm/src/main/kotlin/com/tencent/bkrepo/npm/properties/NpmProperties.kt
- src/backend/npm/biz-npm/src/main/kotlin/com/tencent/bkrepo/npm/service/impl/AbstractNpmService.kt
- src/backend/npm/biz-npm/src/main/kotlin/com/tencent/bkrepo/npm/utils/NpmUtils.kt
- src/backend/npm/biz-npm/src/test/kotlin/com/tencent/bkrepo/npm/utils/NpmUtilsTest.kt
> feat: 支持配置NPM返回的下载路径是否包含仓库ID #2498

- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/util/NodeQueryHelper.kt
> fix: 修复返回有权限路径列表错误 #2515

- src/frontend/devops-repository/src/components/Header/index.vue
- src/frontend/locale/index.js
1、 语言展示汉语为先，English为后
2、 添加语言cookie的过期时间
> feat: repository前端优化 #2555

- src/backend/build.gradle.kts
- src/backend/buildSrc/src/main/kotlin/Versions.kt
- src/backend/job/biz-job/build.gradle.kts
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/preload/ArtifactAccessLogEmbeddingJob.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/preload/ArtifactSimilarityPreloadPlanGenerator.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/preload/ai/SpringAiConfiguration.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/preload/ai/milvus/MilvusClient.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/preload/ai/milvus/MilvusClientProperties.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/preload/ai/milvus/MilvusVectorStore.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/preload/ai/milvus/MilvusVectorStoreProperties.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/preload/ai/milvus/request/CollectionSchema.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/preload/ai/milvus/request/ConsistencyLevel.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/preload/ai/milvus/request/CreateCollectionReq.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/preload/ai/milvus/request/DataType.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/preload/ai/milvus/request/DeleteVectorReq.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/preload/ai/milvus/request/DropCollectionReq.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/preload/ai/milvus/request/FieldSchema.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/preload/ai/milvus/request/HasCollectionReq.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/preload/ai/milvus/request/IndexParam.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/preload/ai/milvus/request/IndexType.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/preload/ai/milvus/request/InsertVectorReq.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/preload/ai/milvus/request/LoadCollectionReq.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/preload/ai/milvus/request/MetricType.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/preload/ai/milvus/request/SearchVectorReq.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/preload/ai/milvus/request/Vector.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/preload/ai/milvus/response/HasCollectionRes.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/preload/ai/milvus/response/MilvusResponse.kt
> fix: 移除milvus-client依赖 #2573

- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/preload/ArtifactAccessLogEmbeddingJob.kt
> feat: 优化向量化任务数据库查询效率 #2596

- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/clean/DeletedNodeCleanupJob.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/config/properties/MigrateRepoStorageJobProperties.kt
> feat: 限制仅在迁移任务开启时检查Node是否在迁移 #2622

- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/preload/ai/milvus/MilvusVectorStore.kt
> bug: 修复生成预加载计划时反序列化失败 #2626

- src/backend/common/common-artifact/artifact-cache/src/main/kotlin/com/tencent/bkrepo/common/artifact/cache/pojo/ArtifactPreloadPlan.kt
- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/filesystem/cleanup/CleanupFileVisitor.kt
- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/filesystem/cleanup/FileRetainResolver.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/file/BasedRepositoryNodeRetainResolver.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/file/ExpireFileResolverConfig.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/file/NodeRetainResolver.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/ExpiredCacheFileCleanupJob.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/preload/ArtifactAccessLogEmbeddingJob.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/preload/ArtifactSimilarityPreloadPlanGenerator.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/preload/SimilarityPathUtils.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/preload/ai/milvus/MilvusClient.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/preload/ai/milvus/MilvusRestApiException.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/metrics/StorageCacheMetrics.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/metrics/StorageCacheMetricsTest.kt
> feat: 支持按项目维度统计保留的缓存大小 #2612

- src/backend/ddc/biz-ddc/src/main/kotlin/com/tencent/bkrepo/ddc/component/PermissionHelper.kt
- src/backend/ddc/biz-ddc/src/main/kotlin/com/tencent/bkrepo/ddc/controller/CompressedBlobController.kt
- src/backend/ddc/biz-ddc/src/main/kotlin/com/tencent/bkrepo/ddc/controller/LegacyReferencesController.kt
- src/backend/ddc/biz-ddc/src/main/kotlin/com/tencent/bkrepo/ddc/controller/ReferencesController.kt
> feat: 支持DDC仓库按路径鉴权 #2635

- src/backend/common/common-artifact/artifact-cache/src/main/kotlin/com/tencent/bkrepo/common/artifact/cache/pojo/ArtifactPreloadPlanCreateRequest.kt
- src/backend/common/common-artifact/artifact-cache/src/main/kotlin/com/tencent/bkrepo/common/artifact/cache/service/ArtifactPreloadPlanService.kt
- src/backend/common/common-artifact/artifact-cache/src/main/kotlin/com/tencent/bkrepo/common/artifact/cache/service/impl/ArtifactPreloadPlanServiceImpl.kt
- src/backend/common/common-artifact/artifact-cache/src/test/kotlin/com/tencent/bkrepo/common/artifact/cache/service/impl/ArtifactPreloadPlanServiceImplTest.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/controller/user/UserArtifactPreloadController.kt
> feat: 支持手动加载制品到缓存 #2640

- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/preload/ArtifactAccessLogEmbeddingJob.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/controller/user/UserEmbeddingController.kt
> feat: 支持动态增加需要向量化访问日志的项目 #2651

- src/backend/common/common-artifact/artifact-cache/src/main/kotlin/com/tencent/bkrepo/common/artifact/cache/dao/ArtifactPreloadStrategyDao.kt
> feat: 支持更新INTELLIGENT类型预加载策略 #2676

- src/backend/common/common-artifact/artifact-cache/src/main/kotlin/com/tencent/bkrepo/common/artifact/cache/service/PreloadListener.kt
- src/backend/common/common-artifact/artifact-cache/src/main/kotlin/com/tencent/bkrepo/common/artifact/cache/service/impl/ArtifactPreloadPlanServiceImpl.kt
- src/backend/common/common-artifact/artifact-cache/src/main/kotlin/com/tencent/bkrepo/common/artifact/cache/service/impl/DefaultPreloadListener.kt
- src/backend/common/common-artifact/artifact-cache/src/main/kotlin/com/tencent/bkrepo/common/artifact/cache/service/impl/DefaultPreloadPlanExecutor.kt
- src/backend/common/common-artifact/artifact-cache/src/test/kotlin/com/tencent/bkrepo/common/artifact/cache/service/impl/ArtifactPreloadPlanServiceImplTest.kt
- src/backend/common/common-artifact/artifact-cache/src/test/kotlin/com/tencent/bkrepo/common/artifact/cache/service/impl/DefaultPreloadPlanExecutorTest.kt
- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/metrics/ArtifactCacheMetrics.kt
- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/metrics/ArtifactMetricsProperties.kt
> feat: 增加预加载数据与大文件缓存未命中监控 #2688

- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/event/listener/ArtifactDownloadListener.kt
> feat: 记录下载的文件大小到审计日志 #2718

- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/cache/preload/ArtifactAccessLogEmbeddingJob.kt
> fix: 修复未复用上月访问记录向量数据 #2728

- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/clean/FileReferenceCleanupJob.kt
> fix: 修复存在同后端存储时可能导致归档文件误删问题 #2742

- src/backend/ddc/biz-ddc/src/main/kotlin/com/tencent/bkrepo/ddc/model/TDdcBlob.kt
- src/backend/ddc/biz-ddc/src/main/kotlin/com/tencent/bkrepo/ddc/model/TDdcBlobRef.kt
- src/backend/ddc/biz-ddc/src/main/kotlin/com/tencent/bkrepo/ddc/pojo/Blob.kt
- src/backend/ddc/biz-ddc/src/main/kotlin/com/tencent/bkrepo/ddc/repository/BlobRefRepository.kt
- src/backend/ddc/biz-ddc/src/main/kotlin/com/tencent/bkrepo/ddc/repository/BlobRepository.kt
- src/backend/ddc/biz-ddc/src/main/kotlin/com/tencent/bkrepo/ddc/service/BlobService.kt
- src/backend/ddc/biz-ddc/src/main/kotlin/com/tencent/bkrepo/ddc/utils/DdcUtils.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/ddc/DdcBlobCleanupJob.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/ddc/ExpiredDdcRefCleanupJob.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/batch/task/ddc/DdcBlobCleanupJobTest.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/batch/task/ddc/DdcTestUtils.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/batch/task/ddc/ExpiredDdcRefCleanupJobTest.kt
> fix: 修复ddc_blob references字段过大导致慢查询问题 #2181

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dispatcher/SubtaskPoller.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dispatcher/SubtaskPushDispatcher.kt
- src/backend/common/common-analysis/src/main/kotlin/com/tencent/bkrepo/common/analysis/pojo/scanner/utils/DockerUtils.kt
> fix: 修复扫描执行服务拉取镜像失败 #2766

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/TemporaryScanTokenServiceImpl.kt
> fix: 修改扫描服务获取镜像Manifest文件失败时抛出的异常 #2778

- src/backend/common/common-artifact/artifact-cache/src/main/kotlin/com/tencent/bkrepo/common/artifact/cache/service/impl/ArtifactPreloadPlanServiceImpl.kt
- src/backend/common/common-artifact/artifact-cache/src/test/kotlin/com/tencent/bkrepo/common/artifact/cache/service/impl/ArtifactPreloadPlanServiceImplTest.kt
- src/backend/common/common-metadata/metadata-service/src/main/kotlin/com/tencent/bkrepo/common/metadata/dao/node/NodeDao.kt
- src/backend/common/common-metadata/metadata-service/src/main/kotlin/com/tencent/bkrepo/common/metadata/service/node/NodeBaseOperation.kt
- src/backend/common/common-metadata/metadata-service/src/main/kotlin/com/tencent/bkrepo/common/metadata/service/node/impl/NodeBaseService.kt
- src/backend/common/common-mongo/src/main/kotlin/com/tencent/bkrepo/common/mongo/dao/sharding/ShardingMongoDao.kt
- src/backend/repository/biz-repository/src/test/kotlin/com/tencent/bkrepo/repository/service/NodeQueryWithoutShardingKeyTest.kt
> fix: 修复预加载计划生成时查询node超时 #2658

- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/clean/DeletedNodeCleanupJob.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/executor/BaseTaskExecutor.kt
> fix: 修复迁移失败Node时未矫正引用数 #2818

- src/backend/ddc/biz-ddc/src/main/kotlin/com/tencent/bkrepo/ddc/repository/BlobRefRepository.kt
- src/backend/ddc/biz-ddc/src/main/kotlin/com/tencent/bkrepo/ddc/service/BlobService.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/context/DdcBlobRefCountCorrectJobContext.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/ddc/DdcBlobRefCountCorrectJob.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/config/properties/DdcBlobRefCountCorrectJobProperties.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/batch/task/ddc/DdcBlobRefCountCorrectJobTest.kt
> fix: 修复重复增加ddc blob引用数 #2825

- src/backend/ddc/biz-ddc/src/main/kotlin/com/tencent/bkrepo/ddc/artifact/repository/DdcLocalRepository.kt
- src/backend/ddc/biz-ddc/src/main/kotlin/com/tencent/bkrepo/ddc/controller/HealthController.kt
- src/backend/ddc/biz-ddc/src/main/kotlin/com/tencent/bkrepo/ddc/service/ReferenceArtifactService.kt
> fix: 修复DDC仓库接口未返回ContentType #2890

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/ScanTaskServiceImpl.kt
> feat: 调整获取分析任务列表接口权限为项目成员可访问 #2904

- .github/workflows/frontend.yml
- src/frontend/devops-op/src/views/repoConfig/components/EditRepoConfigDialog.vue
> bugfix:op仓库管理中点击编辑异常 #2909

- src/backend/common/common-metadata/metadata-service/src/main/kotlin/com/tencent/bkrepo/common/metadata/dao/repo/RepositoryDao.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/controller/user/UserMigrateRepoStorageController.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/MigrateFailedNodeService.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/migrate/MigrateFailedNodeServiceTest.kt
> feat: 支持迁移存储结束后校正存储引用 #2937

- support-files/kubernetes/charts/bkrepo/templates/preview/configmap.yaml
- support-files/kubernetes/charts/bkrepo/values.yaml
> feat: 文件在线预览支持更多的文件类型 #2765

- src/backend/analyst/biz-analyst/build.gradle.kts
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/component/manager/ScanExecutorResultManager.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/component/manager/arrowhead/ArrowheadResultManager.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/component/manager/dependencycheck/DependencyResultManager.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/component/manager/scancode/ScancodeResultManager.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/component/manager/standard/StandardResultManager.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/component/manager/trivy/TrivyResultManager.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/configuration/ScannerConfiguration.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/configuration/ScannerProperties.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dao/ArchiveSubScanTaskDao.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dao/FileScanResultDao.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dao/PlanArtifactLatestSubScanTaskDao.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dao/ScanPlanDao.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/job/ScanTaskCleanupJob.kt
- src/backend/analyst/biz-analyst/src/test/kotlin/com/tencent/bkrepo/analyst/AnalystBaseTest.kt
- src/backend/analyst/biz-analyst/src/test/kotlin/com/tencent/bkrepo/analyst/AnalystTestConfiguration.kt
- src/backend/analyst/biz-analyst/src/test/kotlin/com/tencent/bkrepo/analyst/job/ScanTaskCleanupJobTest.kt
- src/backend/analyst/biz-analyst/src/test/kotlin/com/tencent/bkrepo/analyst/utils/ModelBuildUtils.kt
> feat: 支持清理过期制品分析报告 #393

- src/backend/analyst/api-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/pojo/report/Component.kt
- src/backend/analyst/api-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/pojo/report/ComponentLicense.kt
- src/backend/analyst/api-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/pojo/report/Report.kt
- src/backend/analyst/api-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/pojo/report/SensitiveContent.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/component/ReportExporter.kt
- src/backend/analyst/biz-analyst/src/test/kotlin/com/tencent/bkrepo/analyst/component/ReportExporterTest.kt
- src/backend/analyst/biz-analyst/src/test/kotlin/com/tencent/bkrepo/analyst/utils/ModelBuildUtils.kt
> feat: 支持上报制品分析许可与敏感信息结果 #2970

- .github/workflows/assembly-check.yml
- .github/workflows/backend.yml
- .github/workflows/frontend.yml
- .github/workflows/proxy.yml
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/configuration/ScannerProperties.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/job/ScanTaskCleanupJob.kt
- src/backend/analyst/biz-analyst/src/test/kotlin/com/tencent/bkrepo/analyst/job/ScanTaskCleanupJobTest.kt
> feat: 设置默认不清理制品分析报告 #2986

- src/frontend/devops-repository/src/App.vue
- src/frontend/devops-repository/src/store/index.js
- src/frontend/devops-repository/src/views/repoToken/index.vue
由于token界面监控了用户信息，导致没项目权限的时候，跳转界面会重复请求
> bugfix: token界面会重复发送请求 #2948

- src/frontend/devops-repository/src/store/publicEnum.js
- src/frontend/devops-repository/src/views/repoList/createRepoDialog.vue
- src/frontend/devops-repository/src/views/repoList/index.vue
- src/frontend/devops-repository/src/views/repoSearch/typeSelect.vue
> feat:ci模式下仓库显示优化 #2999

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dao/PlanArtifactLatestSubScanTaskDao.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/job/ScanTaskCleanupJob.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/ScanPlanCorrectServiceImpl.kt
- src/backend/analyst/biz-analyst/src/test/kotlin/com/tencent/bkrepo/analyst/job/ScanTaskCleanupJobTest.kt
> fix: 修复扫描方案预览数据错误 #3006

- src/backend/npm/biz-npm/src/main/kotlin/com/tencent/bkrepo/npm/controller/UserNpmController.kt
- src/backend/npm/biz-npm/src/main/kotlin/com/tencent/bkrepo/npm/properties/NpmProperties.kt
- src/backend/npm/biz-npm/src/main/kotlin/com/tencent/bkrepo/npm/properties/TarballProperties.kt
- src/backend/npm/biz-npm/src/main/kotlin/com/tencent/bkrepo/npm/service/NpmWebService.kt
- src/backend/npm/biz-npm/src/main/kotlin/com/tencent/bkrepo/npm/service/impl/AbstractNpmService.kt
- src/backend/npm/biz-npm/src/main/kotlin/com/tencent/bkrepo/npm/service/impl/NpmClientServiceImpl.kt
- src/backend/npm/biz-npm/src/main/kotlin/com/tencent/bkrepo/npm/service/impl/NpmWebServiceImpl.kt
- src/backend/npm/boot-npm/src/main/resources/bootstrap.yml
> feat: 支持为OHPM单独配置返回的TAR包URL前缀 #3009

- src/frontend/devops-repository/src/views/repoGeneric/index.vue
> bug:前端预览逻辑优化 #3004

- src/frontend/devops-repository/src/components/FilePreview/filePreview.vue
- src/frontend/devops-repository/src/components/FilePreview/outsideFilePreview.vue
- src/frontend/devops-repository/src/router/router.js
> bug:预览现网url进入，预览异常 #3064

- src/backend/common/common-artifact/artifact-api/src/main/kotlin/com/tencent/bkrepo/common/artifact/pojo/configuration/composite/ProxyConfiguration.kt
- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/repository/composite/CompositeRepository.kt
- src/backend/helm/biz-helm/src/main/kotlin/com/tencent/bkrepo/helm/service/impl/AbstractChartService.kt
> feat: 支持为Composite类型仓库设置缓存策略 #3007

- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/manager/StorageManager.kt
> feat: 修复forwardNode未使用正确的存储凭据 #3067

- src/backend/common/common-archive/archive-service/src/main/kotlin/com/tencent/bkrepo/archive/repository/CompressFileDao.kt
- src/backend/common/common-metadata/metadata-service/src/main/kotlin/com/tencent/bkrepo/common/metadata/dao/node/NodeDao.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/MigrateFailedNodeService.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/strategy/ArchivedFileAutoFixStrategy.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/strategy/BaseAutoFixStrategy.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/strategy/FileNotFoundAutoFixStrategy.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/batch/JobBaseTest.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/migrate/strategy/ArchivedFileAutoFixStrategyTest.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/migrate/strategy/FileNotFoundAutoFixStrategyTest.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/migrate/utils/MigrateTestUtils.kt
> feat: 支持自动修复由于归档失败或node的archived标记错误导致的迁移失败 #3097

- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/controller/user/UserMigrateRepoStorageController.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/MigrateFailedNodeService.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/dao/MigrateFailedNodeDao.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/executor/MigrateFailedNodeExecutor.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/strategy/FileNotFoundAutoFixStrategy.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/strategy/MigrateFailedNodeFixer.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/migrate/MigrateFailedNodeServiceTest.kt
> fix: 修复由于存在多个同路径failedNode导致migrating与retryTimes更新错误 #3101

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dispatcher/KubernetesDeploymentDispatcher.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dispatcher/SubtaskPoller.kt
- src/backend/analyst/biz-analyst/src/test/kotlin/com/tencent/bkrepo/analyst/utils/ModelBuildUtils.kt
> fix: 修复deployment类型分发器调用k8s接口频率过高问题 #3155

- src/backend/analyst/api-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/pojo/response/filter/MergedFilterRule.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/component/manager/standard/StandardConverter.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/configuration/ScannerProperties.kt
> impr: 制品分析结果统计优化

- src/backend/common/common-metadata/metadata-service/src/main/kotlin/com/tencent/bkrepo/common/metadata/service/log/OperateLogConfiguration.kt
> fix: 重复创建了LogOperateAspect bean导致生成重复的审计日志 #3182

- src/frontend/core/devops-repository/src/components/PackageCard/index.vue
- src/frontend/core/devops-repository/src/store/actions/repoGeneric.js
- src/frontend/core/devops-repository/src/utils/downloadFile.js
- src/frontend/core/devops-repository/src/views/repoCommon/commonPackageDetail.vue
- src/frontend/core/devops-repository/src/views/repoGeneric/index.vue
- src/frontend/core/devops-repository/src/views/repoScan/artiReport/leak.vue
- src/frontend/core/devops-repository/src/views/repoScan/scanReport/overview.vue
- src/frontend/locale/repository/en-US.json
- src/frontend/locale/repository/zh-CN.json
由于window.open无法设置请求头，下载方法变更。上传使用Promise自定义请求头，需补齐参数X-BKREPO-PROJECT-ID
> bug:上传和下载请求未携带X-BKREPO-PROJECT-ID请求头 #3184

- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/metrics/ArtifactMetrics.kt
- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/metrics/ArtifactMetricsProperties.kt
- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/metrics/filter/LruMeterFilter.kt
- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/metrics/filter/RepositoryPinnedChecker.kt
- src/backend/common/common-artifact/artifact-service/src/test/kotlin/com/tencent/bkrepo/common/artifact/metrics/LruMeterFilterTest.kt
> feat: 支持配置免于流量统计淘汰策略的仓库 #3201

- src/backend/core/huggingface/biz-huggingface/src/main/kotlin/com/tencent/bkrepo/huggingface/artifact/HuggingfaceArtifactInfo.kt
- src/backend/core/huggingface/biz-huggingface/src/main/kotlin/com/tencent/bkrepo/huggingface/artifact/HuggingfaceLocalRepository.kt
- src/backend/core/huggingface/biz-huggingface/src/main/kotlin/com/tencent/bkrepo/huggingface/service/HfCommonService.kt
> feat: huggingface本地仓库禁用拦截 #3229

- src/backend/core/huggingface/biz-huggingface/src/main/kotlin/com/tencent/bkrepo/huggingface/artifact/HuggingfaceArtifactInfo.kt
- src/backend/core/huggingface/biz-huggingface/src/main/kotlin/com/tencent/bkrepo/huggingface/artifact/HuggingfaceLocalRepository.kt
- src/backend/core/huggingface/biz-huggingface/src/main/kotlin/com/tencent/bkrepo/huggingface/artifact/HuggingfaceRemoteRepository.kt
- src/backend/core/huggingface/biz-huggingface/src/main/kotlin/com/tencent/bkrepo/huggingface/service/HfCommonService.kt
> feat: huggingface仓库下载统计 #3227

- src/backend/core/huggingface/api-huggingface/src/main/kotlin/com/tencent/bkrepo/huggingface/constants/constant.kt
- src/backend/core/huggingface/biz-huggingface/src/main/kotlin/com/tencent/bkrepo/huggingface/artifact/HuggingfaceArtifactConfigurer.kt
- src/backend/core/huggingface/biz-huggingface/src/main/kotlin/com/tencent/bkrepo/huggingface/service/ObjectService.kt
- src/backend/core/huggingface/biz-huggingface/src/main/kotlin/com/tencent/bkrepo/huggingface/service/UploadService.kt
1. #3231
2. 上传lfs文件可能权限校验失败
3. lfs文件未设置创建人
> feat: huggingface本地仓库支持regular上传模式 #3231

- src/backend/replication/biz-replication/src/main/kotlin/com/tencent/bkrepo/replication/config/FdtpServerConfiguration.kt
- src/backend/replication/biz-replication/src/main/kotlin/com/tencent/bkrepo/replication/config/startup/FdtpAFTServerApplicationRunner.kt
- src/backend/replication/biz-replication/src/main/kotlin/com/tencent/bkrepo/replication/fdtp/FdtpAFTClientFactory.kt
- src/backend/replication/biz-replication/src/main/kotlin/com/tencent/bkrepo/replication/replica/replicator/base/internal/ClusterArtifactReplicationHandler.kt
- src/backend/replication/biz-replication/src/main/kotlin/com/tencent/bkrepo/replication/replica/replicator/base/internal/FdtpPusher.kt
- src/backend/replication/boot-replication/src/main/resources/bootstrap.yml
> feat: replication中fdtp相关代码根据配置判断是否启动 #1037

- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/repository/remote/RemoteRepository.kt
- src/backend/core/cargo/biz-cargo/src/main/kotlin/com/tencent/bkrepo/cargo/artifact/repository/CargoRemoteRepository.kt
> impr: cargo远程仓库可使用缓存的索引 #3239

- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/repository/remote/RemoteRepository.kt
- src/backend/core/huggingface/api-huggingface/src/main/kotlin/com/tencent/bkrepo/huggingface/pojo/DatasetInfo.kt
- src/backend/core/huggingface/api-huggingface/src/main/kotlin/com/tencent/bkrepo/huggingface/pojo/ModelInfo.kt
- src/backend/core/huggingface/biz-huggingface/src/main/kotlin/com/tencent/bkrepo/huggingface/artifact/HuggingfaceRemoteRepository.kt
- src/backend/core/huggingface/biz-huggingface/src/main/kotlin/com/tencent/bkrepo/huggingface/util/HfApi.kt
> fix: huggingface远程仓库问题修复 #3223

- src/backend/core/oci/biz-oci/src/main/kotlin/com/tencent/bkrepo/oci/service/impl/OciOperationServiceImpl.kt
> fix: 分页查询镜像列表接口报错 #3259

- src/backend/common/common-metadata/metadata-service/src/main/kotlin/com/tencent/bkrepo/common/metadata/service/packages/impl/PackageServiceImpl.kt
> fix: 创建包版本时版本扩展字段错误设置为包扩展字段 #3268

- src/backend/common/common-artifact/artifact-api/src/main/kotlin/com/tencent/bkrepo/common/artifact/pojo/configuration/remote/RemoteCacheConfiguration.kt
- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/repository/remote/RemoteRepository.kt
- src/backend/core/cargo/biz-cargo/src/main/kotlin/com/tencent/bkrepo/cargo/artifact/repository/CargoRemoteRepository.kt
- src/backend/core/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/artifact/GenericRemoteRepository.kt
- src/backend/core/huggingface/biz-huggingface/src/main/kotlin/com/tencent/bkrepo/huggingface/artifact/HuggingfaceArtifactInfo.kt
- src/backend/core/huggingface/biz-huggingface/src/main/kotlin/com/tencent/bkrepo/huggingface/artifact/HuggingfaceLocalRepository.kt
- src/backend/core/huggingface/biz-huggingface/src/main/kotlin/com/tencent/bkrepo/huggingface/artifact/HuggingfaceRemoteRepository.kt
- src/backend/core/huggingface/biz-huggingface/src/main/kotlin/com/tencent/bkrepo/huggingface/artifact/HuggingfaceRevisionInfo.kt
- src/backend/core/huggingface/biz-huggingface/src/main/kotlin/com/tencent/bkrepo/huggingface/artifact/HuggingfaceRevisionInfoResolver.kt
- src/backend/core/huggingface/biz-huggingface/src/main/kotlin/com/tencent/bkrepo/huggingface/controller/DownloadController.kt
- src/backend/core/huggingface/biz-huggingface/src/main/kotlin/com/tencent/bkrepo/huggingface/service/RepoService.kt
- src/backend/core/huggingface/biz-huggingface/src/main/kotlin/com/tencent/bkrepo/huggingface/service/UploadService.kt
- src/backend/core/maven/biz-maven/src/main/kotlin/com/tencent/bkrepo/maven/artifact/repository/MavenRemoteRepository.kt
- src/backend/core/oci/biz-oci/src/main/kotlin/com/tencent/bkrepo/oci/artifact/repository/OciRegistryRemoteRepository.kt
> feat: huggingface远程仓库支持缓存revision info #3233

- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/innercos/client/CosClient.kt
> bug: 修复CosClient分片上传线程池只有一个线程 #3299

- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/clean/DeletedNodeCleanupJob.kt
> fix: 修复未清理sha256为FAKE_SHA256的node #3325

- src/backend/repository/api-repository/src/main/kotlin/com/tencent/bkrepo/repository/pojo/schedule/MetadataRule.kt
- src/backend/repository/api-repository/src/main/kotlin/com/tencent/bkrepo/repository/pojo/schedule/Platform.kt
- src/backend/repository/api-repository/src/main/kotlin/com/tencent/bkrepo/repository/pojo/schedule/ScheduledDownloadConflictStrategy.kt
- src/backend/repository/api-repository/src/main/kotlin/com/tencent/bkrepo/repository/pojo/schedule/ScheduledDownloadRule.kt
- src/backend/repository/api-repository/src/main/kotlin/com/tencent/bkrepo/repository/pojo/schedule/ScheduledDownloadRuleScope.kt
- src/backend/repository/api-repository/src/main/kotlin/com/tencent/bkrepo/repository/pojo/schedule/UserScheduledDownloadRuleCreateRequest.kt
- src/backend/repository/api-repository/src/main/kotlin/com/tencent/bkrepo/repository/pojo/schedule/UserScheduledDownloadRuleQueryRequest.kt
- src/backend/repository/api-repository/src/main/kotlin/com/tencent/bkrepo/repository/pojo/schedule/UserScheduledDownloadRuleUpdateRequest.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/controller/user/UserScheduledDownloadRuleController.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/dao/ScheduledDownloadRuleDao.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/model/TScheduledDownloadRule.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/schedule/ScheduledDownloadRuleService.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/schedule/impl/ScheduledDownloadRuleServiceImpl.kt
- src/backend/repository/biz-repository/src/test/kotlin/com/tencent/bkrepo/repository/service/ScheduledDownloadRuleServiceTest.kt
> feat: 新增预约下载规则管理接口 #3315

- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/manager/StorageManager.kt
- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/repository/context/ArtifactContextHolder.kt
- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/repository/local/LocalRepository.kt
- src/backend/core/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/artifact/GenericLocalRepository.kt
Reverts TencentBlueKing/bk-repo#3476
> Revert "fix: 修复下载forwardNode时返回的checksum错误 #3469"

- src/backend/archive/biz-archive/src/main/kotlin/com/tencent/bkrepo/archive/config/ArchiveCredentialsProperties.kt
> fix: 修复archive服务解析存储配置失败 #3486

- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/manager/NodeResourceFactoryImpl.kt
- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/manager/resource/FsNodeResource.kt
- src/backend/common/common-metadata/metadata-service/src/main/kotlin/com/tencent/bkrepo/common/metadata/service/blocknode/BlockNodeService.kt
- src/backend/common/common-metadata/metadata-service/src/main/kotlin/com/tencent/bkrepo/common/metadata/service/blocknode/RBlockNodeService.kt
- src/backend/common/common-metadata/metadata-service/src/main/kotlin/com/tencent/bkrepo/common/metadata/service/blocknode/impl/BlockNodeServiceImpl.kt
- src/backend/common/common-metadata/metadata-service/src/main/kotlin/com/tencent/bkrepo/common/metadata/service/blocknode/impl/RBlockNodeServiceImpl.kt
- src/backend/common/common-metadata/metadata-service/src/main/kotlin/com/tencent/bkrepo/common/metadata/service/node/impl/NodeMoveCopySupport.kt
- src/backend/common/common-metadata/metadata-service/src/main/kotlin/com/tencent/bkrepo/common/metadata/util/BlockNodeQueryHelper.kt
- src/backend/common/common-metadata/metadata-service/src/main/kotlin/com/tencent/bkrepo/common/metadata/util/NodeBaseServiceHelper.kt
- src/backend/common/common-metadata/metadata-service/src/main/kotlin/com/tencent/bkrepo/common/metadata/util/NodeMoveCopyHelper.kt
- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/OverlaySupport.kt
- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/operation/OverlayOperation.kt
- src/backend/driver/boot-driver/src/main/kotlin/com/tencent/bkrepo/fs/server/service/node/RNodeMoveCopySupport.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/context/NodeCopyJobContext.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/task/other/NodeCopyJob.kt
> feat: 支持复制fs node #3493

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dao/SubScanTaskDao.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/statemachine/TaskStateMachineConfiguration.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/statemachine/TimeoutTaskScheduler.kt
> fix: 修复CREATED状态的子任务超时后未被清理 #3604

- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/dispatcher/SubtaskPushDispatcher.kt
> fix: 修复分发制品分析任务时误释放锁 #3607

- src/backend/replication/biz-replication/src/main/kotlin/com/tencent/bkrepo/replication/replica/replicator/standalone/FederationReplicator.kt
> fix: 和已存在的仓库组成联邦仓库时确保仓库类型一致 #3624

- src/backend/common/common-metadata/metadata-service/src/main/kotlin/com/tencent/bkrepo/common/metadata/interceptor/impl/NodeForbiddenStatusInterceptor.kt
- src/backend/core/conan/biz-conan/src/main/kotlin/com/tencent/bkrepo/conan/exception/ConanExceptionHandler.kt
> fix: 下载禁用制品的响应码不正确 #3630

- src/backend/core/huggingface/biz-huggingface/src/main/kotlin/com/tencent/bkrepo/huggingface/util/RedirectInterceptor.kt
> fix: huggingface远程仓库重定向相对路径的location异常 #3436

- src/backend/core/oci/api-oci/src/main/kotlin/com/tencent/bkrepo/oci/model/ConfigSchema2.kt
- src/backend/core/oci/biz-oci/src/main/kotlin/com/tencent/bkrepo/oci/service/impl/OciOperationServiceImpl.kt
> fix: 访问oci provenance版本详情报参数history缺失 #3649
