TencentBlueKing/bk-repo

- src/backend/common/common-analysis/src/main/kotlin/com/tencent/bkrepo/common/analysis/pojo/scanner/trivy/TrivyScanResult.kt
> fix: 修复Trivy扫描结果为空时解析失败 #48

- src/backend/build.gradle.kts
#17
**Gradle**和**Maven**的依赖排除逻辑不一样，**pom**文件中定义的**exclusion**，**Maven**会根据最短路径原则，选择到的最短路径中如果排除了依赖才排除，而**Gradle**则是全部依赖都排除才会排除，只要有一个依赖间接引用了被排除的依赖，都会引入
```
maven 的行为
the first one will include C in the result,
but the second one won't (because the path with the exclude is shorter) 
and the third one won't (because the path with the exclude was the first one found).
Project -> A -(exclude C)-> B -> C
\-> B -> C
Project -> A -(exclude C)-> B -> C
\-> D -> E -> B -> C
Project -> A -(exclude C)-> B -> C
\-> D -> B -> C
而gradle要A,B,D,E都排除了C，最终才会排除C
```
**Gradle**的`io.spring.dependency-management`插件在构建时为了模拟**Maven**的依赖排除逻辑，会产生大量`detached configurations`，并且耗时很久
调整后执行` ./gradlew clean build -x test` 时间由**3m 28s**降低到**2m 52s**
[Occurrence of dependency-management-plugin leads to bad …
> perf: 添加applyMavenExclusions #17

- src/backend/helm/biz-helm/src/main/kotlin/com/tencent/bkrepo/helm/config/DateConverterConfig.kt
由于取不到lambda表达式的类型参数信息导致创建converter bean失败
#73
> feat: 修复helm服务启动后converter bean创建报错 #73

- src/backend/analyst/api-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/pojo/response/SubtaskResultOverview.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/ScanTaskServiceImpl.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/utils/Converter.kt
- src/frontend/devops-repository/src/views/repoScan/artiReport/index.vue
CLOSE #229 
添加扫描类型字段到预览数据接口，移除报告页对扫描方案详情接口的调用
> 修复制品分报告页面非管理员无权限访问 

- src/backend/maven/biz-maven/src/main/kotlin/com/tencent/bkrepo/maven/service/impl/center/CommitEdgeCenterMavenMetadataServiceImpl.kt
由于DefaultCondition注解只会在非commit-edge架构下生效，所以center节点未创建对应的MavenMetadataService Bean导致服务启动失败
> feat: 修复maven服务启动失败 #224

- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/node/impl/center/CommitEdgeCenterNodeServiceImpl.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/packages/impl/PackageBaseService.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/packages/impl/PackageServiceImpl.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/packages/impl/center/CommitEdgeCenterPackageServiceImpl.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/packages/impl/edge/EdgePackageServiceImpl.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/repo/impl/center/CommitEdgeCenterRepositoryServiceImpl.kt
由于依赖源类型的仓库存在index、metadata等类型的多个package或packageVersion共享的文件，同一个仓库的package属于不同集群时可能会出现跨集群操作错误，因此限制依赖源仓库只允许属于一个集群
> feat: 限制非GENERIC仓库不允许跨集群操作 #224

- src/frontend/devops-repository/src/views/repoScan/scanReport/overview.vue
fix: 制品分析的方案详情页的许可证总数取值不正确,当许可证总数为0时会显示漏洞总数的数据
> fix: 制品分析的方案详情页的许可证总数取值不正确,当许可证总数为0时会显示漏洞总数的数据#374

- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/packages/impl/PackageServiceImpl.kt
增加包版本数改为通过mongo的原子操作来更新。微服务持有版本数在并发下会导致版本数被覆盖的问题。
> bugfix: 修复包管理界面统计版本数和内部实际版本数不一致 #241

- src/frontend/devops-repository/src/views/repoList/index.vue
- src/frontend/devops-software/src/views/repoList/index.vue
feat: p1_26546 【CPack】制品仓库列表标签位置移动到仓库名称右侧显示
> feat: p1_26546 【CPack】制品仓库列表标签位置移动到仓库名称右侧显示 #391

- src/frontend/devops-repository/src/views/repoCommon/metadataTag.vue
fix: 软件源模式下依赖源仓库的制品详情页的元数据展示为空且控制台有报错 #425
> fix: 软件源模式下依赖源仓库的制品详情页的元数据展示为空且控制台有报错 #425

- src/frontend/devops-repository/src/views/repoScan/artiReport/index.vue
fix: 制品详情页点击扫描结果标签进入扫描详情页后点击重新扫描按钮，控制台报错且页面右侧显示空白页 #487
> fix: 制品详情页点击扫描结果标签进入扫描详情页后点击重新扫描按钮，控制台报错且页面右侧显示空白页 #487

- src/frontend/devops-repository/src/views/repoScan/artiReport/artifactInfo.vue
制品分析的方案设置中质量规则设置漏洞数量为0，在扫描记录的详情页不会展示质量规则的 #512
> fix: 制品分析的方案设置中质量规则设置漏洞数量为0，在扫描记录的详情页不会展示质量规则的 #512

- src/frontend/devops-repository/src/views/repoGeneric/index.vue
fix: generic仓库详情页在目录树中搜索文件夹名后列表全屏显示但清除搜索值后目录树不显示 #621
> fix: generic仓库详情页在目录树中搜索文件夹名后列表全屏显示但清除搜索值后目录树不显示 #621

- src/frontend/devops-repository/src/views/repoCommon/commonPackageList.vue
fix: 依赖源仓库中删除制品弹窗，制品标题过长时超出弹窗限制 #768
> fix: 依赖源仓库中删除制品弹窗，制品标题过长时超出弹窗限制 #768

- src/frontend/devops-repository/src/components/ConfirmDialog/index.vue
- src/frontend/devops-repository/src/views/repoCommon/commonPackageDetail.vue
fix: 制品详情页中版本名称过长时，删除弹窗的版本名称超过弹窗的限制 #767
> fix: 制品详情页中版本名称过长时，删除弹窗的版本名称超过弹窗的限制 #767

- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/node/impl/NodeSearchServiceImpl.kt
Generic制品搜索结果没有制品时返回空数组，与有数据时结构不一致，导致浏览器控制台报错
issue #858
> bugfix: Generic制品搜索没有找到制品时浏览器控制台报错 #858

- src/backend/common/common-artifact/artifact-api/src/main/kotlin/com/tencent/bkrepo/common/artifact/path/PathUtils.kt
- src/backend/common/common-artifact/artifact-api/src/test/kotlin/com/tencent/bkrepo/common/artifact/path/PathUtilsTest.kt
- src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/manager/PermissionManager.kt
- src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/artifact/GenericLocalRepository.kt
- src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/controller/GenericController.kt
issue #778
1. batchDownload新增POST请求类型（前端GET请求无法发送请求体）。
2. 可以同时选择文件和目录节点，空目录也会一同下载。
3. 修复了下载多个节点时，公共目录层数过多的问题。
4. 下载的多个节点没有公共目录（公共目录为根目录）时，在zip包添加以仓库名命名的顶层目录，确保解压缩出来只有一个目录。
> feat: 批量下载支持目录节点 #778

- src/backend/maven/biz-maven/src/main/kotlin/com/tencent/bkrepo/maven/artifact/repository/MavenLocalRepository.kt
issue:
1. #1143
maven生成的metadata.xml的checksum文件扩展名为大写，无法被客户端访问到。
> fix: maven元数据摘要文件扩展名错误 #1143

- src/backend/repository/api-repository/src/main/kotlin/com/tencent/bkrepo/repository/pojo/project/ProjectCreateRequest.kt
- src/backend/repository/api-repository/src/main/kotlin/com/tencent/bkrepo/repository/pojo/project/ProjectInfo.kt
- src/backend/repository/api-repository/src/main/kotlin/com/tencent/bkrepo/repository/pojo/project/ProjectMetadata.kt
- src/backend/repository/api-repository/src/main/kotlin/com/tencent/bkrepo/repository/pojo/project/ProjectUpdateRequest.kt
- src/backend/repository/api-repository/src/main/kotlin/com/tencent/bkrepo/repository/pojo/project/UserProjectCreateRequest.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/controller/user/UserProjectController.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/model/TProject.kt
- src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/service/repo/impl/ProjectServiceImpl.kt
- src/backend/repository/biz-repository/src/test/kotlin/com/tencent/bkrepo/repository/service/ProjectServiceTest.kt
> feat: 增加项目元数据字段 #1055

- src/backend/analyst/api-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/message/ScannerMessageCode.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/exception/ArtifactDeletedException.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/TemporaryScanTokenServiceImpl.kt
- src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/statemachine/subtask/action/FinishSubtaskAction.kt
- src/backend/analyst/biz-analyst/src/main/resources/i18n/messages_en.properties
- src/backend/analyst/biz-analyst/src/main/resources/i18n/messages_zh_CN.properties
- src/backend/analyst/biz-analyst/src/main/resources/i18n/messages_zh_TW.properties
> 调整制品分析失败错误日志级别

- src/backend/pypi/biz-pypi/src/main/kotlin/com/tencent/bkrepo/pypi/artifact/repository/PypiLocalRepository.kt
issue:
1. #1272
描述：
访问pypi simple查询接口时，如果url最后不带斜杠，将触发重定向。单体服务模式下重定向url不正确。
> fix: 单体服务pypi simple重定向到错误的url #1272

- src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/SecurityAutoConfiguration.kt
- src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/interceptor/devx/DevxProperties.kt
- src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/interceptor/devx/DevxSrcIpInterceptor.kt
- src/backend/git/biz-git/src/main/kotlin/com/tencent/bkrepo/git/config/GitProperties.kt
- src/backend/git/biz-git/src/main/kotlin/com/tencent/bkrepo/git/config/GitWebConfig.kt
- src/backend/svn/biz-svn/src/main/kotlin/com/tencent/bkrepo/svn/config/SvnConfiguration.kt
- src/backend/svn/biz-svn/src/main/kotlin/com/tencent/bkrepo/svn/config/SvnProperties.kt
> feat: 限制用户可访问的项目资源 #1335

- src/backend/oci/biz-oci/src/main/kotlin/com/tencent/bkrepo/oci/artifact/repository/OciRegistryRemoteRepository.kt
issue:
1. #1342 
描述：
假设oci仓库设置了不包含路径的代理源地址（url形式为`{scheme}://{domain}`而不是`{scheme}://{domain}/{path}`），当访问该代理源的资源返回401时，oci仓库将根据响应头的内容请求用于获取token的url，此时该url的查询参数scope多了斜杠`repository:/{repository}:{accessSet}`，导致获取的token在用于后续请求资源时可能无法通过鉴权。
> fix: oci仓库访问不包含路径的代理源地址时可能无法通过鉴权 #1342

- src/backend/svn/biz-svn/src/main/kotlin/com/tencent/bkrepo/svn/interceptor/ChangeAncestorProxyHandler.kt
> fix: 修复SVN-PROXY响应的Content-Length设置错误导致SVN拉取失败 #1572

- src/frontend/devops-repository/src/views/repoCommon/commonPackageDetail.vue
issue:
1. #1576
描述:
1. 根据[SemVer2](https://semver.org/)规范，版本号可能包含"+"。
2. 根据[RFC 3986](https://www.rfc-editor.org/rfc/rfc3986#section-2.2)，没有特殊意义的保留字符需要预先编码，版本号中可能包含保留字符。
3. 未编码的"+"字符在后端将被解释为空格。
> fix: 页面下载版本号带+的制品失败 #1576

- src/backend/npm/biz-npm/src/main/kotlin/com/tencent/bkrepo/npm/utils/NpmUtils.kt
1. #1715 
1. 包名格式为`@{scope}/{name}`的包，其文件名为`{name}-{version}.tgz`，此处逻辑不兼容这种格式的包名。
> fix: npm scope类型包的版本号解析错误 #1715

- src/backend/replication/biz-replication/src/main/kotlin/com/tencent/bkrepo/replication/replica/replicator/standalone/ClusterReplicator.kt
1. #1736
1.  当前仅npm和oci仓库制品的`manifestPath`不为`null`，目标节点创建分发版本时将`manifestPath`设置为`null`会导致使用`manifestPath`的一些功能出现问题。这两种仓库的manifest文件路径在源节点和目标节点是相同的。
> fix: 同步制品时保留manifestPath #1736

- src/backend/oci/api-oci/src/main/kotlin/com/tencent/bkrepo/oci/pojo/artifact/OciArtifactInfo.kt
- src/backend/oci/biz-oci/src/main/kotlin/com/tencent/bkrepo/oci/artifact/repository/OciRegistryRemoteRepository.kt
- src/backend/oci/biz-oci/src/main/kotlin/com/tencent/bkrepo/oci/artifact/resolver/OciTagArtifactInfoResolver.kt
- src/backend/oci/biz-oci/src/main/kotlin/com/tencent/bkrepo/oci/controller/user/OciTagController.kt
1. #1705 
1. 当远程仓库的代理url包含命名空间时（例如`https://registry-1.docker.io/library`），`/v2/`被拼接在命名空间之后（`https://registry-1.docker.io/library/v2/{image}/tags/list`），导致查询不到`tags`。
> fix: oci远程仓库url包含命名空间时无法查询tags #1705

- src/backend/oci/biz-oci/src/main/kotlin/com/tencent/bkrepo/oci/util/OciResponseUtils.kt
1. #1694 
1. `UriBuilder.host()`方法会对传入的host进行url编码，当`oci.domain`为`<ip>:<port>`形式时，构建的`Uri`对象的`host`被编码为`<ip>%3A<port>`，导致`location`响应头的地址为`<scheme>:<ip>%3A<port>`。
2. docker客户端对`location`响应头进行转换([docker-ce](https://github.com/docker/docker-ce/blob/master/components/engine/vendor/github.com/containerd/containerd/remotes/docker/pusher.go#L231))，在转换过程中，使用go标准库`net/url`对`location`中的`host`进行url解码操作([net/url](https://github.com/golang/go/blob/master/src/net/url/url.go#L233-L234))。
3. 根据[RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986#section-3.2.2)：
> URI producing applications must not use percent-encoding in host unless it is used to represent a UTF-8 character sequence.
在host中url编码仅可用于非ASC II 字符，而`:`(`%3A`)为ASC II字符。
`net/url`的url解码操作遵循RFC 3986，在这种情况下将抛出`invalid URL escape …
> fix: oci指定端口号时无法推送镜像 #1694

- src/backend/common/common-artifact/artifact-api/build.gradle.kts
- src/backend/common/common-artifact/artifact-api/src/main/kotlin/com/tencent/bkrepo/common/artifact/api/ArtifactInfo.kt
- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/repository/context/ArtifactContext.kt
- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/repository/context/ArtifactDownloadContext.kt
- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/repository/context/ArtifactQueryContext.kt
- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/repository/context/ArtifactRemoveContext.kt
- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/repository/context/ArtifactSearchContext.kt
- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/repository/context/ArtifactUploadContext.kt
1. #1024 
1. 原有的`ArtifactContext.copy`方法不复制`projectId`、`repoName`、`storageCredentials`属性，仅适用于组合仓库。
2. 新增`ArtifactInfo.copy`方法，使用传入的`projectId`和`repoName`构造新实例，并复制其它所有属性。
> feat: 新增适用于虚拟仓库的ArtifactContext复制方法 #1024

- src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/artifact/GenericRemoteRepository.kt
1.  #2217 
可能导致部分特定名称目录下的资源无法访问（例如META-INF目录）
> fix: Generic远程仓库代理请求路径未编码 #2217

- src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/s3/S3Storage.kt
S3Storage的defaultTransferManager的初始化存在并发问题，可能会被重复初始化，并导致被错误关闭   #2344
> fix: S3传输管理器的初始化方式线程不安全 #2344

- src/frontend/devops-repository/src/views/repoGeneric/index.vue
- src/frontend/locale/repository/en-US.json
- src/frontend/locale/repository/zh-CN.json
1. 表格selection头部渲染，暂时无法做出下拉菜单（最新版虽然可以渲染selection，但是下拉菜单仍会遮挡，无法使用）[https://github.com/TencentBlueKing/bkui-vue2/issues/559](url)
2. selection第一个checkbox样式变换暂时无法实现（与上配套）
> feat：制品列表展示的记录数和批量选择优化 #2261

- src/frontend/devops-repository/src/views/repoConfig/index.vue
authMode初始值为undefined，此值于created才赋予值，计算属性高于创建完属性，故会开始报一段错。
> fix: 仓库设置控制台报错,无法读取bkiamv3Check #2806

- src/backend/common/common-metadata/metadata-service/src/main/kotlin/com/tencent/bkrepo/common/metadata/dao/node/NodeDao.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/controller/user/UserMigrateRepoStorageController.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/MigrateFailedNodeService.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/dao/MigrateFailedNodeDao.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/executor/MigrateFailedNodeExecutor.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/executor/handler/DefaultMigrateFailedHandler.kt
- src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/migrate/model/TMigrateFailedNode.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/migrate/MigrateFailedNodeServiceTest.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/migrate/executor/ExecutorBaseTest.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/migrate/executor/MigrateExecutorTest.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/migrate/executor/MigrateFailedNodeExecutorTest.kt
- src/backend/job/biz-job/src/test/kotlin/com/tencent/bkrepo/job/migrate/utils/MigrateTestUtils.kt
issue:  #3088 
1. 修复存在同路径已删除node迁移失败时无法保存failedNode，支持手动创建缺失的failedNode
2. 支持更新node归档状态
3. 修复迁移失败Node时未正确判断node是否已归档
> fix: 修复迁移失败Node时未正确判断node是否已归档 #3088

- src/backend/common/common-api/src/main/kotlin/com/tencent/bkrepo/common/api/util/AuthenticationUtil.kt
> fix: oci远程仓库代理部分镜像源认证失败 #3257

- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/manager/StorageManager.kt
- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/repository/context/ArtifactContextHolder.kt
- src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/repository/local/LocalRepository.kt
- src/backend/core/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/artifact/GenericLocalRepository.kt
- src/backend/replication/biz-replication/src/test/kotlin/com/tencent/bkrepo/replication/fdtp/FdtpAFTTest.kt
1. #3469 
考虑forward操作与业务强相关，且repository层中会根据node设置相关响应数据，因此将forward操作移至repository层
> fix: 修复下载forwardNode时候返回的checksum错误 #3469
